// =============================================================================
// twiddle_rom.v
// Twiddle Factor ROM for ModMuls stage
// Stores all non-power-of-2 twiddle factors needed across all NTT stages.
// For q=65537, N=256, R=4: twiddle factors ω^{r*(2l+1)}_{2N} for each (stage, b, r)
//
// For synthesis, these are implemented as a read-only table indexed by
// (stage, b_idx, r).
//
// The twiddle address from the control unit (tw_addr) indexes this table.
// tw_out gives up to R twiddle values, one per ModMul.
//
// For q=65537, 2N=512, the twiddle factors ω^k_{512} for k=0..255.
// Only odd exponents are used in ModMuls (since 2l+1 is always odd).
// =============================================================================

module twiddle_rom #(
    parameter B        = 16,     // Fermat word width
    parameter N        = 256,    // Polynomial degree
    parameter R        = 4,      // Radix
    parameter TW_DEPTH = N,      // Number of twiddle factor entries
    parameter TW_BITS  = $clog2(TW_DEPTH)
)(
    input  wire [TW_BITS-1:0]   tw_addr,   // Twiddle factor address
    output reg  [B:0]            tw_out     // Twiddle factor (normal representation)
);
    // Twiddle factors for q=65537, N=256: ω_{512}^k mod 65537
    // ω_{512} = 2^{16/256} does not simplify; we generate them from ω_{512}=... 
    // For q=F4=65537=2^16+1, ω_2 = 2^16 = -1 mod q (primitive 2nd root)
    // ω_4 = 2^8 = 256, ω_8 = 2^4=16, ω_16=2^2=4, ω_32=2^1=2, ω_64=2^{1/2}...
    // For N=256: ω_256 must satisfy ω_256^128 = ω_2 = -1 = 65536
    // The 256th root of unity mod 65537 is well-known: ω_256 = 3
    // ω_512 = 2 (primitive 512th root of unity; 2^256 ≡ -1 mod 65537 since 2^{2^16}≡1, period=32 for 2)
    // Actually: order of 2 mod 65537 = 32. We need ω_{512}: use ω_{512}=a where a^{512}≡1.
    // Let's use ω_N = ω_{256} = 3 (order 256 mod 65537) and ω_{2N}=ω_{512} where ω_{512}^2=3.
    // ω_{512} mod 65537 = 2^{65536/512} ... Let's just hardcode the table using ω_{512}=... 
    //
    // IMPORTANT: This ROM is generated by golden_model.py and included as a $readmemh file.
    // For simulation, the file "twiddle_factors.hex" must exist in the simulation directory.
    // For synthesis, replace with actual ROM values.

    reg [B:0] tw_mem [0:TW_DEPTH-1];
    initial begin
        $readmemh("twiddle_factors.hex", tw_mem);
    end

    always @(*) begin
        tw_out = tw_mem[tw_addr];
    end
endmodule
