// =============================================================================
// twiddle_rom.v
// Twiddle Factor ROM for ModMuls stage
// Stores ω_{2N}^k mod q for k = 0..2N-1 (512 entries for N=256).
//
// For stage s, group b, element r:
//   twiddle[r] = ω_{2N}^{r * (2*bitrev(b)+1) * delta_idx}
//
// The control unit outputs tw_step = (2*bitrev(b)+1) * delta_idx.
// This module looks up tw_out[r] = mem[ (r * tw_step) % (2*N) ] for r=0..R-1.
//
// IMPORTANT: This ROM is generated by golden_model.py and included as a $readmemh file.
// For simulation, the file "twiddle_factors.hex" must exist (512 entries).
// =============================================================================

module twiddle_rom #(
    parameter B        = 16,     // Fermat word width
    parameter N        = 256,    // Polynomial degree
    parameter R        = 4,      // Radix
    parameter TW_DEPTH = 2*N,    // 512 entries: ω_{2N}^k for k=0..2N-1
    parameter TW_BITS  = $clog2(TW_DEPTH)  // 9 bits
)(
    input  wire [TW_BITS-1:0]    tw_step,   // (2*bitrev(b)+1)*delta_idx from ctrl
    output wire [R*(B+1)-1:0]    tw_out     // R twiddle factors (normal rep.)
);
    reg [B:0] tw_mem [0:TW_DEPTH-1];
    initial begin
        $readmemh("twiddle_factors.hex", tw_mem);
    end

    // Output R twiddle factors: tw_out[r] = mem[(r * tw_step) % (2*N)]
    genvar r;
    generate
        for (r = 0; r < R; r = r + 1) begin : gen_tw
            wire [TW_BITS-1:0] idx = (r * tw_step) % TW_DEPTH;
            assign tw_out[r*(B+1) +: (B+1)] = tw_mem[idx];
        end
    endgenerate
endmodule

// Single-entry lookup for stage-specific/custom twiddle exponents.
module twiddle_lookup #(
    parameter B        = 16,
    parameter N        = 256,
    parameter TW_DEPTH = 2*N,
    parameter TW_BITS  = $clog2(TW_DEPTH)
)(
    input  wire [TW_BITS-1:0] tw_idx,
    output wire [B:0]         tw_val
);
    reg [B:0] tw_mem [0:TW_DEPTH-1];
    initial begin
        $readmemh("twiddle_factors.hex", tw_mem);
    end

    assign tw_val = tw_mem[tw_idx];
endmodule
