// =============================================================================
// tb_ntt_top.v
// Testbench for ntt_top.v — NTT Polynomial Multiplier
// Tests full polynomial multiplication c = a * b mod (x^256 + 1) mod 65537
//
// Usage:
//   1. python golden_model.py   (generates hex files in rtl/ directory)
//   2. Run simulation: xvlog/xelab/xsim or iverilog/vvp
//
// Checks output against expected_out.hex
// =============================================================================

`timescale 1ns/1ps

module tb_ntt_top;
    // ---- Parameters ----------------------------------------------------------
    localparam B     = 16;
    localparam N     = 256;
    localparam R     = 4;
    localparam WWIDTH = B + 1;  // 17

    // ---- DUT signals ---------------------------------------------------------
    reg             clk, rst, start;
    reg  [WWIDTH-1:0] data_in_a, data_in_b;
    wire [WWIDTH-1:0] data_out;
    wire              done;

    // ---- Instantiate DUT -----------------------------------------------------
    ntt_top #(.B(B), .N(N), .R(R)) dut (
        .clk      (clk),
        .rst      (rst),
        .start    (start),
        .data_in_a(data_in_a),
        .data_in_b(data_in_b),
        .data_out (data_out),
        .done     (done)
    );

    // ---- Clock generation ----------------------------------------------------
    initial clk = 0;
    always  #5 clk = ~clk;  // 100 MHz (10 ns period)

    // ---- Test vectors --------------------------------------------------------
    reg [WWIDTH-1:0] input_a  [0:N-1];
    reg [WWIDTH-1:0] input_b  [0:N-1];
    reg [WWIDTH-1:0] expected [0:N-1];
    reg [WWIDTH-1:0] got_out  [0:N-1];
    integer i, errors;

    // ---- Stimulus ------------------------------------------------------------
    initial begin
        // Load test vectors from files generated by golden_model.py
        $readmemh("input_a.hex",      input_a);
        $readmemh("input_b.hex",      input_b);
        $readmemh("expected_out.hex", expected);

        // Dump waveform
        $dumpfile("tb_ntt_top.vcd");
        $dumpvars(0, tb_ntt_top);

        // Reset
        rst = 1; start = 0; data_in_a = 0; data_in_b = 0;
        repeat(4) @(posedge clk);
        @(negedge clk);
        rst = 0;

        // Load polynomials: N cycles, one coefficient per cycle
        @(negedge clk);
        start = 1;
        for (i = 0; i < N; i = i + 1) begin
            data_in_a = input_a[i];
            data_in_b = input_b[i];
            @(negedge clk);
        end
        start = 0;
        data_in_a = 0;
        data_in_b = 0;

        // Wait for done signal (timeout after 100k cycles)
        begin : wait_loop
            integer timeout_cnt;
            timeout_cnt = 0;
            while (!done && timeout_cnt < 100000) begin
                @(posedge clk);
                timeout_cnt = timeout_cnt + 1;
            end
            if (timeout_cnt >= 100000) begin
                $display("TIMEOUT: done never asserted after 100k cycles");
                $finish;
            end
        end

        // Collect output: N cycles
        @(posedge done);
        for (i = 0; i < N; i = i + 1) begin
            @(posedge clk);
            got_out[i] = data_out;
        end

        // Compare with expected
        errors = 0;
        for (i = 0; i < N; i = i + 1) begin
            if (got_out[i] !== expected[i]) begin
                $display("MISMATCH at coeff[%0d]: got=%0h expected=%0h", i, got_out[i], expected[i]);
                errors = errors + 1;
            end
        end

        if (errors == 0)
            $display("PASS: All %0d coefficients match!", N);
        else
            $display("FAIL: %0d errors out of %0d coefficients", errors, N);

        #100;
        $finish;
    end

    // ---- Monitor -------------------------------------------------------------
    initial begin
        $monitor("[%0t] state=? done=%b data_out=%0h", $time, done, data_out);
    end

endmodule
