// =============================================================================
// hier_d7_L4_top.v   (GENERATED by scripts/gen_hier_dN_L4.py)
// 7-variate hierarchical NTT negacyclic polyMul.  L=4, N=L^7=16384.
// Axes i6..i0.  bank=(sum i_j) mod L; pos=i1+L*i2+...+L^5*i_6.
// Pipeline taps d5/d8/d12.  ntt_start uses state_d[1]/valid_d[1] (and
// state_d[5]/valid_d[5] for FWD_L0) so the start aligns with data arrival
// at the sub-NTT (fixes the last-issue direction-flip bug).
// =============================================================================
`ifndef _HIER_D7_L4_TOP_GUARD
`define _HIER_D7_L4_TOP_GUARD

module hier_d7_L4_top #(
    parameter B       = 16,
    parameter L       = 4,
    parameter N       = L*L*L*L*L*L*L,
    parameter WWIDTH  = B + 1,
    parameter LOGN    = 14,
    parameter TW_BITS = LOGN + 1
)(
    input  wire              clk,
    input  wire              rst,
    input  wire              start,
    input  wire [WWIDTH-1:0] data_in_a,
    input  wire [WWIDTH-1:0] data_in_b,
    output reg  [WWIDTH-1:0] data_out,
    output reg               data_out_valid,
    output reg               done,
    output reg  [31:0]       cycle_count
);

    localparam [5:0]
        ST_IDLE        = 6'd0,
        ST_LOAD        = 6'd1,
        ST_FWD_L0_A    = 6'd2,
        ST_FWD_XTW1_A  = 6'd3,
        ST_FWD_L1_A    = 6'd4,
        ST_FWD_XTW2_A  = 6'd5,
        ST_FWD_L2_A    = 6'd6,
        ST_FWD_XTW3_A  = 6'd7,
        ST_FWD_L3_A    = 6'd8,
        ST_FWD_XTW4_A  = 6'd9,
        ST_FWD_L4_A    = 6'd10,
        ST_FWD_XTW5_A  = 6'd11,
        ST_FWD_L5_A    = 6'd12,
        ST_FWD_XTW6_A  = 6'd13,
        ST_FWD_L6_A    = 6'd14,
        ST_FWD_L0_B    = 6'd15,
        ST_FWD_XTW1_B  = 6'd16,
        ST_FWD_L1_B    = 6'd17,
        ST_FWD_XTW2_B  = 6'd18,
        ST_FWD_L2_B    = 6'd19,
        ST_FWD_XTW3_B  = 6'd20,
        ST_FWD_L3_B    = 6'd21,
        ST_FWD_XTW4_B  = 6'd22,
        ST_FWD_L4_B    = 6'd23,
        ST_FWD_XTW5_B  = 6'd24,
        ST_FWD_L5_B    = 6'd25,
        ST_FWD_XTW6_B  = 6'd26,
        ST_FWD_L6_B    = 6'd27,
        ST_PWM         = 6'd28,
        ST_INV_L6      = 6'd29,
        ST_INV_XTW6    = 6'd30,
        ST_INV_L5      = 6'd31,
        ST_INV_XTW5    = 6'd32,
        ST_INV_L4      = 6'd33,
        ST_INV_XTW4    = 6'd34,
        ST_INV_L3      = 6'd35,
        ST_INV_XTW3    = 6'd36,
        ST_INV_L2      = 6'd37,
        ST_INV_XTW2    = 6'd38,
        ST_INV_L1      = 6'd39,
        ST_INV_XTW1    = 6'd40,
        ST_INV_L0      = 6'd41,
        ST_OUTPUT      = 6'd42,
        ST_DONE        = 6'd43;

    localparam integer SCAN_CYCLES = N / L;
    localparam integer DRAIN       = 12;
    localparam integer SCAN_LEN    = SCAN_CYCLES + DRAIN;

    reg [5:0] state;
    reg [LOGN:0]   op_count;
    wire           issue_valid;

    reg [5:0] state_d   [1:12];
    reg [LOGN:0]   opcnt_d   [1:12];
    reg            valid_d   [1:12];
    integer ds;
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            for (ds = 1; ds <= 12; ds = ds + 1) begin
                state_d[ds] <= 6'd0;
                opcnt_d[ds] <= {(LOGN+1){1'b0}};
                valid_d[ds] <= 1'b0;
            end
        end else begin
            state_d[1] <= state; opcnt_d[1] <= op_count; valid_d[1] <= issue_valid;
            for (ds = 2; ds <= 12; ds = ds + 1) begin
                state_d[ds] <= state_d[ds-1];
                opcnt_d[ds] <= opcnt_d[ds-1];
                valid_d[ds] <= valid_d[ds-1];
            end
        end
    end

    assign issue_valid =
        (state == ST_LOAD)    ? (op_count < N) :
        (state == ST_OUTPUT)  ? (op_count < N) :
        (state == ST_IDLE)    ? 1'b0 :
        (state == ST_DONE)    ? 1'b0 :
                                (op_count < SCAN_CYCLES);

    localparam integer LANES     = L;
    localparam integer DEPTH     = L*L*L*L*L*L;
    localparam integer LOG_LANES = 2;
    localparam integer LOG_DEPTH = 12;

    wire [LOG_LANES-1:0] op_a = op_count[1:0];
    wire [LOG_LANES-1:0] op_b = op_count[3:2];
    wire [LOG_LANES-1:0] op_c = op_count[5:4];
    wire [LOG_LANES-1:0] op_d = op_count[7:6];
    wire [LOG_LANES-1:0] op_e = op_count[9:8];
    wire [LOG_LANES-1:0] op_f = op_count[11:10];

    wire [LOG_LANES-1:0] load_i0 = op_count[1:0];
    wire [LOG_LANES-1:0] load_i1 = op_count[3:2];
    wire [LOG_LANES-1:0] load_i2 = op_count[5:4];
    wire [LOG_LANES-1:0] load_i3 = op_count[7:6];
    wire [LOG_LANES-1:0] load_i4 = op_count[9:8];
    wire [LOG_LANES-1:0] load_i5 = op_count[11:10];
    wire [LOG_LANES-1:0] load_i6 = op_count[13:12];
    wire [LOG_LANES-1:0] load_bank = (load_i0 + load_i1 + load_i2 + load_i3 + load_i4 + load_i5 + load_i6) & 2'h3;
    reg  [LOG_LANES-1:0] load_bank_d1;
    always @(posedge clk) load_bank_d1 <= load_bank;
    wire [LOG_DEPTH-1:0] load_pos  = {load_i6, load_i5, load_i4, load_i3, load_i2, load_i1};

    wire [LOG_LANES-1:0] load_i0_d5 = opcnt_d[5][1:0];
    wire [LOG_LANES-1:0] load_i1_d5 = opcnt_d[5][3:2];
    wire [LOG_LANES-1:0] load_i2_d5 = opcnt_d[5][5:4];
    wire [LOG_LANES-1:0] load_i3_d5 = opcnt_d[5][7:6];
    wire [LOG_LANES-1:0] load_i4_d5 = opcnt_d[5][9:8];
    wire [LOG_LANES-1:0] load_i5_d5 = opcnt_d[5][11:10];
    wire [LOG_LANES-1:0] load_i6_d5 = opcnt_d[5][13:12];
    wire [LOG_LANES-1:0] load_bank_d5 = (load_i0_d5 + load_i1_d5 + load_i2_d5 + load_i3_d5 + load_i4_d5 + load_i5_d5 + load_i6_d5) & 2'h3;
    wire [LOG_DEPTH-1:0] load_pos_d5  = {load_i6_d5, load_i5_d5, load_i4_d5, load_i3_d5, load_i2_d5, load_i1_d5};

    wire [LOG_LANES-1:0] rshift_op = (op_a + op_b + op_c + op_d + op_e + op_f) & 2'h3;

    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i1_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i2_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i3_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i4_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i5_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i6_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_broadcast_pack;
    wire [LANES*LOG_DEPTH-1:0] rpos_zero_pack;
    genvar gk;
    generate
        for (gk = 0; gk < LANES; gk = gk + 1) begin : g_rpos
            assign rpos_axis_i1_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {op_f, op_e, op_d, op_c, op_b, gk[1:0]};
            assign rpos_axis_i2_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {op_f, op_e, op_d, op_c, gk[1:0], op_b};
            assign rpos_axis_i3_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {op_f, op_e, op_d, gk[1:0], op_c, op_b};
            assign rpos_axis_i4_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {op_f, op_e, gk[1:0], op_d, op_c, op_b};
            assign rpos_axis_i5_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {op_f, gk[1:0], op_e, op_d, op_c, op_b};
            assign rpos_axis_i6_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {gk[1:0], op_f, op_e, op_d, op_c, op_b};
            assign rpos_broadcast_pack[gk*LOG_DEPTH +: LOG_DEPTH] = {op_f, op_e, op_d, op_c, op_b, op_a};
            assign rpos_zero_pack     [gk*LOG_DEPTH +: LOG_DEPTH] = {LOG_DEPTH{1'b0}};
        end
    endgenerate

    wire [LANES*LOG_DEPTH-1:0] wpos_i1_d5, wpos_i1_d8, wpos_i1_d12;
    wire [LANES*LOG_DEPTH-1:0] wpos_i2_d5, wpos_i2_d8, wpos_i2_d12;
    wire [LANES*LOG_DEPTH-1:0] wpos_i3_d5, wpos_i3_d8, wpos_i3_d12;
    wire [LANES*LOG_DEPTH-1:0] wpos_i4_d5, wpos_i4_d8, wpos_i4_d12;
    wire [LANES*LOG_DEPTH-1:0] wpos_i5_d5, wpos_i5_d8, wpos_i5_d12;
    wire [LANES*LOG_DEPTH-1:0] wpos_i6_d5, wpos_i6_d8, wpos_i6_d12;
    wire [LANES*LOG_DEPTH-1:0] wpos_bc_d5, wpos_bc_d8, wpos_bc_d12;
    generate
        for (gk = 0; gk < LANES; gk = gk + 1) begin : g_wpos
            assign wpos_i1_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[5][11:10], opcnt_d[5][9:8], opcnt_d[5][7:6], opcnt_d[5][5:4], opcnt_d[5][3:2], gk[1:0]};
            assign wpos_i2_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[5][11:10], opcnt_d[5][9:8], opcnt_d[5][7:6], opcnt_d[5][5:4], gk[1:0], opcnt_d[5][3:2]};
            assign wpos_i3_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[5][11:10], opcnt_d[5][9:8], opcnt_d[5][7:6], gk[1:0], opcnt_d[5][5:4], opcnt_d[5][3:2]};
            assign wpos_i4_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[5][11:10], opcnt_d[5][9:8], gk[1:0], opcnt_d[5][7:6], opcnt_d[5][5:4], opcnt_d[5][3:2]};
            assign wpos_i5_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[5][11:10], gk[1:0], opcnt_d[5][9:8], opcnt_d[5][7:6], opcnt_d[5][5:4], opcnt_d[5][3:2]};
            assign wpos_i6_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {gk[1:0], opcnt_d[5][11:10], opcnt_d[5][9:8], opcnt_d[5][7:6], opcnt_d[5][5:4], opcnt_d[5][3:2]};
            assign wpos_bc_d5[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[5][11:10], opcnt_d[5][9:8], opcnt_d[5][7:6], opcnt_d[5][5:4], opcnt_d[5][3:2], opcnt_d[5][1:0]};
            assign wpos_i1_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[8][11:10], opcnt_d[8][9:8], opcnt_d[8][7:6], opcnt_d[8][5:4], opcnt_d[8][3:2], gk[1:0]};
            assign wpos_i2_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[8][11:10], opcnt_d[8][9:8], opcnt_d[8][7:6], opcnt_d[8][5:4], gk[1:0], opcnt_d[8][3:2]};
            assign wpos_i3_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[8][11:10], opcnt_d[8][9:8], opcnt_d[8][7:6], gk[1:0], opcnt_d[8][5:4], opcnt_d[8][3:2]};
            assign wpos_i4_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[8][11:10], opcnt_d[8][9:8], gk[1:0], opcnt_d[8][7:6], opcnt_d[8][5:4], opcnt_d[8][3:2]};
            assign wpos_i5_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[8][11:10], gk[1:0], opcnt_d[8][9:8], opcnt_d[8][7:6], opcnt_d[8][5:4], opcnt_d[8][3:2]};
            assign wpos_i6_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {gk[1:0], opcnt_d[8][11:10], opcnt_d[8][9:8], opcnt_d[8][7:6], opcnt_d[8][5:4], opcnt_d[8][3:2]};
            assign wpos_bc_d8[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[8][11:10], opcnt_d[8][9:8], opcnt_d[8][7:6], opcnt_d[8][5:4], opcnt_d[8][3:2], opcnt_d[8][1:0]};
            assign wpos_i1_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[12][11:10], opcnt_d[12][9:8], opcnt_d[12][7:6], opcnt_d[12][5:4], opcnt_d[12][3:2], gk[1:0]};
            assign wpos_i2_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[12][11:10], opcnt_d[12][9:8], opcnt_d[12][7:6], opcnt_d[12][5:4], gk[1:0], opcnt_d[12][3:2]};
            assign wpos_i3_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[12][11:10], opcnt_d[12][9:8], opcnt_d[12][7:6], gk[1:0], opcnt_d[12][5:4], opcnt_d[12][3:2]};
            assign wpos_i4_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[12][11:10], opcnt_d[12][9:8], gk[1:0], opcnt_d[12][7:6], opcnt_d[12][5:4], opcnt_d[12][3:2]};
            assign wpos_i5_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[12][11:10], gk[1:0], opcnt_d[12][9:8], opcnt_d[12][7:6], opcnt_d[12][5:4], opcnt_d[12][3:2]};
            assign wpos_i6_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {gk[1:0], opcnt_d[12][11:10], opcnt_d[12][9:8], opcnt_d[12][7:6], opcnt_d[12][5:4], opcnt_d[12][3:2]};
            assign wpos_bc_d12[gk*LOG_DEPTH +: LOG_DEPTH] = {opcnt_d[12][11:10], opcnt_d[12][9:8], opcnt_d[12][7:6], opcnt_d[12][5:4], opcnt_d[12][3:2], opcnt_d[12][1:0]};
        end
    endgenerate

    wire [LOG_LANES-1:0] wshift_d5 = (opcnt_d[5][1:0] + opcnt_d[5][3:2] + opcnt_d[5][5:4] + opcnt_d[5][7:6] + opcnt_d[5][9:8] + opcnt_d[5][11:10]) & 2'h3;
    wire [LOG_LANES-1:0] wshift_d8 = (opcnt_d[8][1:0] + opcnt_d[8][3:2] + opcnt_d[8][5:4] + opcnt_d[8][7:6] + opcnt_d[8][9:8] + opcnt_d[8][11:10]) & 2'h3;
    wire [LOG_LANES-1:0] wshift_d12 = (opcnt_d[12][1:0] + opcnt_d[12][3:2] + opcnt_d[12][5:4] + opcnt_d[12][7:6] + opcnt_d[12][9:8] + opcnt_d[12][11:10]) & 2'h3;

    reg [WWIDTH-1:0] in_a_d [1:5];
    reg [WWIDTH-1:0] in_b_d [1:5];
    integer dd;
    always @(posedge clk) begin
        in_a_d[1] <= data_in_a; in_b_d[1] <= data_in_b;
        for (dd = 2; dd <= 5; dd = dd + 1) begin
            in_a_d[dd] <= in_a_d[dd-1]; in_b_d[dd] <= in_b_d[dd-1];
        end
    end

    reg  [L*WWIDTH-1:0]  mul_a_pack;
    reg  [L*WWIDTH-1:0]  mul_b_pack;
    wire [L*WWIDTH-1:0]  mul_out_pack;
    wire [L*WWIDTH-1:0]  tw_pack;
    wire [L*TW_BITS-1:0] tw_idx_pack;

    function [TW_BITS-1:0] inv_tw_idx;
        input [TW_BITS-1:0] idx;
        begin inv_tw_idx = (((2*N) - idx) % (2*N)); end
    endfunction

    genvar tg;
    generate
        for (tg = 0; tg < L; tg = tg + 1) begin : gen_tw_lanes
            wire [LOG_LANES-1:0] oa_d0 = op_a;
            wire [LOG_LANES-1:0] ob_d0 = op_b;
            wire [LOG_LANES-1:0] oc_d0 = op_c;
            wire [LOG_LANES-1:0] od_d0 = op_d;
            wire [LOG_LANES-1:0] oe_d0 = op_e;
            wire [LOG_LANES-1:0] of_d0 = op_f;
            wire [TW_BITS-1:0] tw_fwd_l0_idx = (oa_d0 + L*ob_d0 + L*L*oc_d0 + L*L*L*od_d0 + L*L*L*L*oe_d0 + L*L*L*L*L*of_d0 + L*L*L*L*L*L*tg) % (2*N);
            wire [TW_BITS-1:0] tw_xtw1_idx = (2*L*L*L*L*L*of_d0*tg) % (2*N);
            wire [TW_BITS-1:0] tw_xtw2_idx = (2*L*L*L*L*tg*(L*oe_d0 + of_d0)) % (2*N);
            wire [TW_BITS-1:0] tw_xtw3_idx = (2*L*L*L*tg*(L*L*od_d0 + L*oe_d0 + of_d0)) % (2*N);
            wire [TW_BITS-1:0] tw_xtw4_idx = (2*L*L*tg*(L*L*L*oc_d0 + L*L*od_d0 + L*oe_d0 + of_d0)) % (2*N);
            wire [TW_BITS-1:0] tw_xtw5_idx = (2*L*tg*(L*L*L*L*ob_d0 + L*L*L*oc_d0 + L*L*od_d0 + L*oe_d0 + of_d0)) % (2*N);
            wire [TW_BITS-1:0] tw_xtw6_idx = (2*tg*(L*L*L*L*L*oa_d0 + L*L*L*L*ob_d0 + L*L*L*oc_d0 + L*L*od_d0 + L*oe_d0 + of_d0)) % (2*N);
            wire [LOG_LANES-1:0] oa_d7 = opcnt_d[7][1:0];
            wire [LOG_LANES-1:0] ob_d7 = opcnt_d[7][3:2];
            wire [LOG_LANES-1:0] oc_d7 = opcnt_d[7][5:4];
            wire [LOG_LANES-1:0] od_d7 = opcnt_d[7][7:6];
            wire [LOG_LANES-1:0] oe_d7 = opcnt_d[7][9:8];
            wire [LOG_LANES-1:0] of_d7 = opcnt_d[7][11:10];
            wire [TW_BITS-1:0] tw_inv_l0_idx_d7 = inv_tw_idx((oa_d7 + L*ob_d7 + L*L*oc_d7 + L*L*L*od_d7 + L*L*L*L*oe_d7 + L*L*L*L*L*of_d7 + L*L*L*L*L*L*tg) % (2*N));
            wire [TW_BITS-1:0] tw_inv_xtw1_idx = inv_tw_idx(tw_xtw1_idx);
            wire [TW_BITS-1:0] tw_inv_xtw2_idx = inv_tw_idx(tw_xtw2_idx);
            wire [TW_BITS-1:0] tw_inv_xtw3_idx = inv_tw_idx(tw_xtw3_idx);
            wire [TW_BITS-1:0] tw_inv_xtw4_idx = inv_tw_idx(tw_xtw4_idx);
            wire [TW_BITS-1:0] tw_inv_xtw5_idx = inv_tw_idx(tw_xtw5_idx);
            wire [TW_BITS-1:0] tw_inv_xtw6_idx = inv_tw_idx(tw_xtw6_idx);
            assign tw_idx_pack[tg*TW_BITS +: TW_BITS] =
                (state_d[7] == ST_INV_L0) ? tw_inv_l0_idx_d7 :
                ((state == ST_FWD_L0_A) || (state == ST_FWD_L0_B)) ? tw_fwd_l0_idx :
                ((state == ST_FWD_XTW1_A) || (state == ST_FWD_XTW1_B)) ? tw_xtw1_idx :
                ((state == ST_FWD_XTW2_A) || (state == ST_FWD_XTW2_B)) ? tw_xtw2_idx :
                ((state == ST_FWD_XTW3_A) || (state == ST_FWD_XTW3_B)) ? tw_xtw3_idx :
                ((state == ST_FWD_XTW4_A) || (state == ST_FWD_XTW4_B)) ? tw_xtw4_idx :
                ((state == ST_FWD_XTW5_A) || (state == ST_FWD_XTW5_B)) ? tw_xtw5_idx :
                ((state == ST_FWD_XTW6_A) || (state == ST_FWD_XTW6_B)) ? tw_xtw6_idx :
                (state == ST_INV_XTW6) ? tw_inv_xtw6_idx :
                (state == ST_INV_XTW5) ? tw_inv_xtw5_idx :
                (state == ST_INV_XTW4) ? tw_inv_xtw4_idx :
                (state == ST_INV_XTW3) ? tw_inv_xtw3_idx :
                (state == ST_INV_XTW2) ? tw_inv_xtw2_idx :
                (state == ST_INV_XTW1) ? tw_inv_xtw1_idx :
                {TW_BITS{1'b0}};

            twiddle_gen #(.B(B), .LOGN(LOGN), .REGISTERED(1)) u_tw (
                .clk(clk), .idx(tw_idx_pack[tg*TW_BITS +: TW_BITS]),
                .tw_out(tw_pack[tg*WWIDTH +: WWIDTH]));
            (* DONT_TOUCH = "true" *) reg [WWIDTH-1:0] mul_a_r;
            (* DONT_TOUCH = "true" *) reg [WWIDTH-1:0] mul_b_r;
            always @(posedge clk) begin
                mul_a_r <= mul_a_pack[tg*WWIDTH +: WWIDTH];
                mul_b_r <= mul_b_pack[tg*WWIDTH +: WWIDTH];
            end
            mod_mul_fermat #(.B(B), .PIPELINED(1)) u_mul (
                .clk(clk), .rst(rst), .a(mul_a_r), .b(mul_b_r),
                .result(mul_out_pack[tg*WWIDTH +: WWIDTH]));
        end
    endgenerate

    reg [L*WWIDTH-1:0] ntt_in_pack;
    reg [L*WWIDTH-1:0] ntt_in_reg;
    reg                ntt_start, ntt_start_d1;
    reg                ntt_inverse, ntt_inverse_d1;
    always @(posedge clk) begin
        ntt_in_reg <= ntt_in_pack;
        ntt_start_d1 <= ntt_start; ntt_inverse_d1 <= ntt_inverse;
    end
    always @(*) begin
        ntt_start = 1'b0; ntt_inverse = 1'b0;
        if ((state_d[5] == ST_FWD_L0_A || state_d[5] == ST_FWD_L0_B) && valid_d[5])
            ntt_start = 1'b1;
        else case (state_d[1])
            ST_FWD_L1_A, ST_FWD_L1_B, ST_FWD_L2_A, ST_FWD_L2_B, ST_FWD_L3_A, ST_FWD_L3_B, ST_FWD_L4_A, ST_FWD_L4_B, ST_FWD_L5_A, ST_FWD_L5_B, ST_FWD_L6_A, ST_FWD_L6_B: ntt_start = valid_d[1];
            ST_INV_L0, ST_INV_L1, ST_INV_L2, ST_INV_L3, ST_INV_L4, ST_INV_L5, ST_INV_L6: begin ntt_start = valid_d[1]; ntt_inverse = 1'b1; end
            default: ;
        endcase
    end

    wire [L*WWIDTH-1:0] ntt_out_pack;
    sub_ntt4_bidir #(.B(B)) u_subntt (
        .clk(clk), .rst(rst), .start(ntt_start_d1), .inverse(ntt_inverse_d1),
        .in_norm(ntt_in_reg), .out_norm(ntt_out_pack), .valid());

    `define BMEM_DECL(NM) \
        wire [LANES*WWIDTH-1:0]    NM``_rdata; \
        reg  [LOG_LANES-1:0]       NM``_rshift; \
        reg  [LANES*LOG_DEPTH-1:0] NM``_rpos; \
        reg  [LOG_LANES-1:0]       NM``_wshift; \
        reg  [LANES*LOG_DEPTH-1:0] NM``_wpos; \
        reg  [LANES*WWIDTH-1:0]    NM``_wdata; \
        reg  [LANES-1:0]           NM``_we; \
        banked_mem #(.WWIDTH(WWIDTH), .LANES(LANES), .DEPTH(DEPTH), \
                     .LOG_LANES(LOG_LANES), .LOG_DEPTH(LOG_DEPTH), \
                     .READ_LATENCY(0), .STORAGE("bram")) u_``NM ( \
            .clk(clk), \
            .rshift(NM``_rshift), .rpos_pack(NM``_rpos), .rdata_pack(NM``_rdata), \
            .wshift(NM``_wshift), .wpos_pack(NM``_wpos), .wdata_pack(NM``_wdata), \
            .we_pack(NM``_we) );
    `BMEM_DECL(mem_a)
    `BMEM_DECL(mem_b)
    `BMEM_DECL(mem_scratch)

    wire [LANES*WWIDTH-1:0] raw_a_rdata   = mem_a_rdata;
    wire [LANES*WWIDTH-1:0] raw_b_rdata   = mem_b_rdata;
    wire [LANES*WWIDTH-1:0] scratch_rdata = mem_scratch_rdata;

    function [LANES*WWIDTH-1:0] broadcastN;
        input [WWIDTH-1:0] v; integer bi;
        begin broadcastN = {LANES*WWIDTH{1'b0}};
            for (bi=0; bi<LANES; bi=bi+1) broadcastN[bi*WWIDTH +: WWIDTH] = v;
        end
    endfunction

    always @(*) begin
        mem_a_rshift = 2'd0; mem_a_rpos = rpos_zero_pack;
        mem_a_wshift = 2'd0; mem_a_wpos = rpos_zero_pack;
        mem_a_wdata = {LANES*WWIDTH{1'b0}}; mem_a_we = {LANES{1'b0}};
        case (state)
            ST_FWD_L0_A: begin mem_a_rshift = rshift_op; mem_a_rpos = rpos_axis_i6_pack; end
            ST_PWM:      begin mem_a_rshift = rshift_op; mem_a_rpos = rpos_broadcast_pack; end
            ST_INV_L6:  begin mem_a_rshift = rshift_op; mem_a_rpos = rpos_broadcast_pack; end
            ST_OUTPUT:   begin mem_a_rshift = 2'd0; mem_a_rpos[load_bank*LOG_DEPTH +: LOG_DEPTH] = load_pos; end
            default: ;
        endcase
        // INV_L0 final result -> mem_a (d12, axis_i6)
        if (state_d[12] == ST_INV_L0 && valid_d[12]) begin
            mem_a_wshift = wshift_d12; mem_a_wpos = wpos_i6_d12;
            mem_a_wdata = mul_out_pack; mem_a_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_FWD_L6_A && valid_d[8]) begin
            mem_a_wshift = wshift_d8; mem_a_wpos = wpos_bc_d8;
            mem_a_wdata = ntt_out_pack; mem_a_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_PWM && valid_d[5]) begin
            mem_a_wshift = wshift_d5; mem_a_wpos = wpos_bc_d5;
            mem_a_wdata = mul_out_pack; mem_a_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_LOAD && valid_d[5]) begin
            mem_a_wpos[load_bank_d5*LOG_DEPTH +: LOG_DEPTH] = load_pos_d5;
            mem_a_wdata = broadcastN(in_a_d[5]); mem_a_we[load_bank_d5] = 1'b1;
        end
    end

    always @(*) begin
        mem_b_rshift = 2'd0; mem_b_rpos = rpos_zero_pack;
        mem_b_wshift = 2'd0; mem_b_wpos = rpos_zero_pack;
        mem_b_wdata = {LANES*WWIDTH{1'b0}}; mem_b_we = {LANES{1'b0}};
        case (state)
            ST_FWD_L0_B: begin mem_b_rshift = rshift_op; mem_b_rpos = rpos_axis_i6_pack; end
            ST_PWM:      begin mem_b_rshift = rshift_op; mem_b_rpos = rpos_broadcast_pack; end
            default: ;
        endcase
        if (state_d[8] == ST_FWD_L6_B && valid_d[8]) begin
            mem_b_wshift = wshift_d8; mem_b_wpos = wpos_bc_d8;
            mem_b_wdata = ntt_out_pack; mem_b_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_LOAD && valid_d[5]) begin
            mem_b_wpos[load_bank_d5*LOG_DEPTH +: LOG_DEPTH] = load_pos_d5;
            mem_b_wdata = broadcastN(in_b_d[5]); mem_b_we[load_bank_d5] = 1'b1;
        end
    end

    always @(*) begin
        mem_scratch_rshift = 2'd0; mem_scratch_rpos = rpos_zero_pack;
        mem_scratch_wshift = 2'd0; mem_scratch_wpos = rpos_zero_pack;
        mem_scratch_wdata = {LANES*WWIDTH{1'b0}}; mem_scratch_we = {LANES{1'b0}};
        case (state)
            ST_FWD_XTW1_A, ST_FWD_XTW1_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i6_pack; end
            ST_FWD_XTW2_A, ST_FWD_XTW2_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i4_pack; end
            ST_FWD_XTW3_A, ST_FWD_XTW3_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i3_pack; end
            ST_FWD_XTW4_A, ST_FWD_XTW4_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i2_pack; end
            ST_FWD_XTW5_A, ST_FWD_XTW5_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i1_pack; end
            ST_FWD_XTW6_A, ST_FWD_XTW6_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_broadcast_pack; end
            ST_FWD_L1_A, ST_FWD_L1_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i5_pack; end
            ST_FWD_L2_A, ST_FWD_L2_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i4_pack; end
            ST_FWD_L3_A, ST_FWD_L3_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i3_pack; end
            ST_FWD_L4_A, ST_FWD_L4_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i2_pack; end
            ST_FWD_L5_A, ST_FWD_L5_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i1_pack; end
            ST_FWD_L6_A, ST_FWD_L6_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_broadcast_pack; end
            ST_INV_XTW6: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_broadcast_pack; end
            ST_INV_XTW5: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i1_pack; end
            ST_INV_XTW4: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i2_pack; end
            ST_INV_XTW3: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i3_pack; end
            ST_INV_XTW2: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i4_pack; end
            ST_INV_XTW1: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i5_pack; end
            ST_INV_L5: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i1_pack; end
            ST_INV_L4: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i2_pack; end
            ST_INV_L3: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i3_pack; end
            ST_INV_L2: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i4_pack; end
            ST_INV_L1: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i5_pack; end
            ST_INV_L0: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = rpos_axis_i6_pack; end
            default: ;
        endcase
        if ((state_d[12] == ST_FWD_L0_A || state_d[12] == ST_FWD_L0_B) && valid_d[12]) begin
            mem_scratch_wshift = wshift_d12; mem_scratch_wpos = wpos_i6_d12;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[8] == ST_FWD_L1_A || state_d[8] == ST_FWD_L1_B) && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i5_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[8] == ST_FWD_L2_A || state_d[8] == ST_FWD_L2_B) && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i4_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[8] == ST_FWD_L3_A || state_d[8] == ST_FWD_L3_B) && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i3_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[8] == ST_FWD_L4_A || state_d[8] == ST_FWD_L4_B) && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i2_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[8] == ST_FWD_L5_A || state_d[8] == ST_FWD_L5_B) && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i1_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_INV_L6 && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_bc_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_INV_L5 && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i1_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_INV_L4 && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i2_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_INV_L3 && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i3_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_INV_L2 && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i4_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[8] == ST_INV_L1 && valid_d[8]) begin
            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_i5_d8;
            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[5] == ST_FWD_XTW1_A || state_d[5] == ST_FWD_XTW1_B) && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i6_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[5] == ST_FWD_XTW2_A || state_d[5] == ST_FWD_XTW2_B) && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i4_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[5] == ST_FWD_XTW3_A || state_d[5] == ST_FWD_XTW3_B) && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i3_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[5] == ST_FWD_XTW4_A || state_d[5] == ST_FWD_XTW4_B) && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i2_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[5] == ST_FWD_XTW5_A || state_d[5] == ST_FWD_XTW5_B) && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i1_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if ((state_d[5] == ST_FWD_XTW6_A || state_d[5] == ST_FWD_XTW6_B) && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_bc_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_INV_XTW6 && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_bc_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_INV_XTW5 && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i1_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_INV_XTW4 && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i2_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_INV_XTW3 && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i3_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_INV_XTW2 && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i4_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
        else if (state_d[5] == ST_INV_XTW1 && valid_d[5]) begin
            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = wpos_i5_d5;
            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {LANES{1'b1}};
        end
    end

    integer ci;
    always @(*) begin
        ntt_in_pack = {L*WWIDTH{1'b0}};
        if (state_d[5] == ST_FWD_L0_A || state_d[5] == ST_FWD_L0_B)
            ntt_in_pack = mul_out_pack;
        else case (state_d[1])
            ST_FWD_L1_A, ST_FWD_L1_B, ST_FWD_L2_A, ST_FWD_L2_B, ST_FWD_L3_A, ST_FWD_L3_B, ST_FWD_L4_A, ST_FWD_L4_B, ST_FWD_L5_A, ST_FWD_L5_B, ST_FWD_L6_A, ST_FWD_L6_B,
            ST_INV_L0, ST_INV_L1, ST_INV_L2, ST_INV_L3, ST_INV_L4, ST_INV_L5: ntt_in_pack = scratch_rdata;
            ST_INV_L6: ntt_in_pack = mem_a_rdata;
            default: ;
        endcase
    end

    always @(*) begin
        mul_a_pack = {L*WWIDTH{1'b0}}; mul_b_pack = {L*WWIDTH{1'b0}};
        if (state_d[8] == ST_INV_L0) begin
            mul_a_pack = ntt_out_pack; mul_b_pack = tw_pack;
        end else begin
            for (ci = 0; ci < L; ci = ci + 1) begin
                case (state_d[1])
                    ST_FWD_L0_A: begin
                        mul_a_pack[ci*WWIDTH +: WWIDTH] = raw_a_rdata[ci*WWIDTH +: WWIDTH];
                        mul_b_pack[ci*WWIDTH +: WWIDTH] = tw_pack[ci*WWIDTH +: WWIDTH]; end
                    ST_FWD_L0_B: begin
                        mul_a_pack[ci*WWIDTH +: WWIDTH] = raw_b_rdata[ci*WWIDTH +: WWIDTH];
                        mul_b_pack[ci*WWIDTH +: WWIDTH] = tw_pack[ci*WWIDTH +: WWIDTH]; end
                    ST_FWD_XTW1_A, ST_FWD_XTW1_B, ST_FWD_XTW2_A, ST_FWD_XTW2_B, ST_FWD_XTW3_A, ST_FWD_XTW3_B, ST_FWD_XTW4_A, ST_FWD_XTW4_B, ST_FWD_XTW5_A, ST_FWD_XTW5_B, ST_FWD_XTW6_A, ST_FWD_XTW6_B,
                    ST_INV_XTW1, ST_INV_XTW2, ST_INV_XTW3, ST_INV_XTW4, ST_INV_XTW5, ST_INV_XTW6: begin
                        mul_a_pack[ci*WWIDTH +: WWIDTH] = scratch_rdata[ci*WWIDTH +: WWIDTH];
                        mul_b_pack[ci*WWIDTH +: WWIDTH] = tw_pack[ci*WWIDTH +: WWIDTH]; end
                    ST_PWM: begin
                        mul_a_pack[ci*WWIDTH +: WWIDTH] = mem_a_rdata[ci*WWIDTH +: WWIDTH];
                        mul_b_pack[ci*WWIDTH +: WWIDTH] = mem_b_rdata[ci*WWIDTH +: WWIDTH]; end
                    default: ;
                endcase
            end
        end
    end

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state <= ST_IDLE; op_count <= {(LOGN+1){1'b0}}; cycle_count <= 32'd0;
            data_out <= {WWIDTH{1'b0}}; data_out_valid <= 1'b0; done <= 1'b0;
        end else begin
            data_out_valid <= 1'b0;
            case (state)
                ST_IDLE: begin done<=1'b0; op_count<={(LOGN+1){1'b0}}; cycle_count<=32'd0; if (start) state<=ST_LOAD; end
                ST_LOAD: begin cycle_count<=cycle_count+1;
                    if (op_count == N+11) begin op_count<=0; state<=ST_FWD_L0_A; end else op_count<=op_count+1; end
                ST_FWD_L0_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW1_A; end else op_count<=op_count+1; end
                ST_FWD_XTW1_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L1_A; end else op_count<=op_count+1; end
                ST_FWD_L1_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW2_A; end else op_count<=op_count+1; end
                ST_FWD_XTW2_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L2_A; end else op_count<=op_count+1; end
                ST_FWD_L2_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW3_A; end else op_count<=op_count+1; end
                ST_FWD_XTW3_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L3_A; end else op_count<=op_count+1; end
                ST_FWD_L3_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW4_A; end else op_count<=op_count+1; end
                ST_FWD_XTW4_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L4_A; end else op_count<=op_count+1; end
                ST_FWD_L4_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW5_A; end else op_count<=op_count+1; end
                ST_FWD_XTW5_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L5_A; end else op_count<=op_count+1; end
                ST_FWD_L5_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW6_A; end else op_count<=op_count+1; end
                ST_FWD_XTW6_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L6_A; end else op_count<=op_count+1; end
                ST_FWD_L6_A: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L0_B; end else op_count<=op_count+1; end
                ST_FWD_L0_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW1_B; end else op_count<=op_count+1; end
                ST_FWD_XTW1_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L1_B; end else op_count<=op_count+1; end
                ST_FWD_L1_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW2_B; end else op_count<=op_count+1; end
                ST_FWD_XTW2_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L2_B; end else op_count<=op_count+1; end
                ST_FWD_L2_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW3_B; end else op_count<=op_count+1; end
                ST_FWD_XTW3_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L3_B; end else op_count<=op_count+1; end
                ST_FWD_L3_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW4_B; end else op_count<=op_count+1; end
                ST_FWD_XTW4_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L4_B; end else op_count<=op_count+1; end
                ST_FWD_L4_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW5_B; end else op_count<=op_count+1; end
                ST_FWD_XTW5_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L5_B; end else op_count<=op_count+1; end
                ST_FWD_L5_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_XTW6_B; end else op_count<=op_count+1; end
                ST_FWD_XTW6_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_FWD_L6_B; end else op_count<=op_count+1; end
                ST_FWD_L6_B: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_PWM; end else op_count<=op_count+1; end
                ST_PWM: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L6; end else op_count<=op_count+1; end
                ST_INV_L6: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_XTW6; end else op_count<=op_count+1; end
                ST_INV_XTW6: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L5; end else op_count<=op_count+1; end
                ST_INV_L5: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_XTW5; end else op_count<=op_count+1; end
                ST_INV_XTW5: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L4; end else op_count<=op_count+1; end
                ST_INV_L4: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_XTW4; end else op_count<=op_count+1; end
                ST_INV_XTW4: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L3; end else op_count<=op_count+1; end
                ST_INV_L3: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_XTW3; end else op_count<=op_count+1; end
                ST_INV_XTW3: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L2; end else op_count<=op_count+1; end
                ST_INV_L2: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_XTW2; end else op_count<=op_count+1; end
                ST_INV_XTW2: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L1; end else op_count<=op_count+1; end
                ST_INV_L1: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_XTW1; end else op_count<=op_count+1; end
                ST_INV_XTW1: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_INV_L0; end else op_count<=op_count+1; end
                ST_INV_L0: begin cycle_count<=cycle_count+1;
                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<=ST_OUTPUT; end else op_count<=op_count+1; end
                ST_OUTPUT: begin cycle_count<=cycle_count+1;
                    data_out <= mem_a_rdata[load_bank_d1*WWIDTH +: WWIDTH];
                    data_out_valid <= (op_count >= 1) && (op_count < N+1);
                    if (op_count == N+1) begin op_count<=0; state<=ST_DONE; end else op_count<=op_count+1; end
                ST_DONE: done <= 1'b1;
            endcase
        end
    end

endmodule
`endif
