// =============================================================================
// tb_ntt_top.v
// Testbench for ntt_top.v — NTT Polynomial Multiplier
// Tests full polynomial multiplication c = a * b mod (x^256 + 1) mod 65537
//
// Usage:
//   1. python golden_model.py   (generates hex files in sim/ directory)
//   2. Run simulation: iverilog/vvp
//
// Checks output against expected_out.hex
// =============================================================================

`timescale 1ns/1ps

module tb_ntt_top;
    // ---- Parameters ----------------------------------------------------------
    localparam B     = 16;
    localparam N     = 256;
    localparam R     = 4;
    localparam WWIDTH = B + 1;  // 17

    // ---- DUT signals ---------------------------------------------------------
    reg             clk, rst, start;
    reg  [WWIDTH-1:0] data_in_a, data_in_b;
    wire [WWIDTH-1:0] data_out;
    wire              done;

    // ---- Instantiate DUT -----------------------------------------------------
    ntt_top #(.B(B), .N(N), .R(R)) dut (
        .clk      (clk),
        .rst      (rst),
        .start    (start),
        .data_in_a(data_in_a),
        .data_in_b(data_in_b),
        .data_out (data_out),
        .done     (done)
    );

    // ---- Clock generation ----------------------------------------------------
    initial clk = 0;
    always  #5 clk = ~clk;  // 100 MHz (10 ns period)

    // ---- Test vectors --------------------------------------------------------
    reg [WWIDTH-1:0] input_a  [0:N-1];
    reg [WWIDTH-1:0] input_b  [0:N-1];
    reg [WWIDTH-1:0] expected [0:N-1];
    reg [WWIDTH-1:0] got_out  [0:N-1];
    integer i, errors;

    // ---- Stimulus ------------------------------------------------------------
    initial begin
        // Load test vectors from files generated by golden_model.py
        $readmemh("input_a.hex",      input_a);
        $readmemh("input_b.hex",      input_b);
        $readmemh("expected_out.hex", expected);

        // Dump waveform
        $dumpfile("bin/tb_ntt_top.vcd");
        $dumpvars(0, tb_ntt_top);

        // Reset
        rst = 1; start = 0; data_in_a = 0; data_in_b = 0;
        repeat(4) @(posedge clk);
        @(negedge clk);
        rst = 0;

        // Load polynomials: N cycles, one coefficient per cycle
        @(negedge clk);
        start = 1;
        for (i = 0; i < N; i = i + 1) begin
            data_in_a = input_a[i];
            data_in_b = input_b[i];
            @(negedge clk);
        end
        start = 0;
        data_in_a = 0;
        data_in_b = 0;

        // Wait for done signal (timeout after 100k cycles)
        begin : wait_loop
            integer timeout_cnt;
            timeout_cnt = 0;
            while (!done && timeout_cnt < 100000) begin
                @(posedge clk);
                timeout_cnt = timeout_cnt + 1;
            end
            if (timeout_cnt >= 100000) begin
                $display("TIMEOUT: done never asserted after 100k cycles");
                $finish;
            end
        end

        // done is now high after OUTPUT phase completes. The seq_cnt is frozen at its last value
        // to keep the final data stable. The mem_banks have 1-cycle registered read latency.
        // During the OUTPUT state (before done), seq_cnt increments 0..N-1, presenting addresses.
        // The first data appears one cycle after address presentation.
        // We must READ DURING OUTPUT PHASE while seq_cnt is incrementing, not after.
        
        // Strategy: Monitor OUTPUT state and capture data while it's active
        errors = 0;
        fork
            begin
                wait(done);
                #10000 $finish;  // Prevent timeout hang
            end
            begin
                integer read_idx = 0;
                while (read_idx < N) begin
                    @(posedge clk);
                    if (dut.u_ctrl.fsm_state == 3'd6) begin  // OUTPUT state = 6
                        got_out[read_idx] = data_out;
                        if (read_idx < 10 || read_idx == 255)
                            $display("DEBUG: Read coeff[%0d] = %0h (expected %0h) from data_out", read_idx, data_out, expected[read_idx]);
                        read_idx = read_idx + 1;
                    end
                end
            end
        join_any


        // Compare with expected
        errors = 0;
        for (i = 0; i < N; i = i + 1) begin
            if (got_out[i] !== expected[i]) begin
                if (i < 10 || i == 255)
                    $display("MISMATCH at coeff[%0d]: got=%0h expected=%0h", i, got_out[i], expected[i]);
                errors = errors + 1;
            end
        end

        if (errors == 0)
            $display("PASS: All %0d coefficients match!", N);
        else
            $display("FAIL: %0d errors out of %0d coefficients", errors, N);

        #100;
        $finish;
    end

    // ---- Monitor after OUTPUT completes -----------------------------------------
    initial begin
        @(negedge done);
        repeat(10) @(posedge clk);
        $display("Monitoring after done signal...");
        // Wait for next done
        wait(!done);
    end


endmodule
