#!/usr/bin/env python3
"""
compare_table.py
================
Read synthesis metrics_raw.txt files for ntt_top (R=8) and bivar_ntt_top
across N=64, 128, 256 and print the main comparison table for the paper.

Falls back to simulation-only (cycle counts) when synthesis results are absent.

Usage:
    python scripts/compare_table.py
    python scripts/compare_table.py --n-values 64 128 256
"""

from __future__ import annotations

import argparse
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT  = SCRIPT_DIR.parent
SYNTH_DIR  = REPO_ROOT / "synth"

# Simulation-derived cycle counts (TOTAL: LOAD + compute + OUTPUT).
# Generated by: python sim/measure_ntt_cycles.py
# Updated after time-shared ModMul + 2-stage pipelined mod_mul_fermat
# (PIPE_LATENCY=2 inserts 1 stall cycle between consecutive groups).
# Scope reduced to R=4 and R=8 (R=16 dropped from the paper).
SIM_CYCLES_NTT = {
    (4,  64):  2177, (4,  128): 2177, (4,  256): 2177,
    (8,  64):  1149, (8,  128): 1149, (8,  256): 1149,
}

# bivar cycles from regression (formula: 2N + 7M + 3L, L=8 fixed)
SIM_CYCLES_BIVAR = {64: 208, 128: 392, 256: 760}

# Predicted DSP counts (analytic).
# Phase 4 architecture: ntt_top now uses a single time-shared ModMul bank
# (R pipelined mod_mul_fermat instances) matching the paper. Synthesis-confirmed
# DSP counts: R=8 -> 8 DSPs, R=4 -> 4 DSPs.
# bivar: 8 DSPs (8 lanes x 1 mod_mul_fermat each, time-shared).
PRED_DSP_NTT8  = 8
PRED_DSP_BIVAR = 8

# Paper reference values from Xing et al. (2025), Table IV
# Device: Virtex-7 xc7vx690tffg1761-3 (note: different part from our xc7k160tfbg484-2)
# Architecture: time-shared ModMuls bank (R DSPs for NTT+INTT+PWM), pipelined mod_mul_fermat.
# Memory: upper/lower half cohabitation => zero separate I/O load phase.
# Cycles = TOTAL for 2 NTTs + 1 PWM + 1 INTT (no additional I/O overhead).
PAPER_REF_NTT = {
    # (R, N): {LUT, DSP, Fmax_MHz, cycles}
    # Scope reduced to R=4 and R=8 (R=16 dropped from our implementation).
    (4,  256): {"LUT": 1690, "DSP": 4,  "Fmax": 301.0, "cycles": 876},
    (8,  256): {"LUT": 3596, "DSP": 8,  "Fmax": 301.0, "cycles": 389},
}


def read_metrics(path: Path) -> dict | None:
    if not path.exists():
        return None
    m: dict = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, _, v = line.partition("=")
            m[k.strip()] = v.strip()
    return m


def get_int(d: dict | None, key: str) -> int | None:
    if d is None:
        return None
    v = d.get(key)
    if v is None:
        return None
    try:
        return int(v)
    except ValueError:
        return None


def get_float(d: dict | None, key: str) -> float | None:
    if d is None:
        return None
    v = d.get(key)
    if v is None:
        return None
    try:
        return float(v)
    except ValueError:
        return None


def fmt(v, fmt_str=""):
    if v is None:
        return "N/A"
    if fmt_str:
        return format(v, fmt_str)
    return str(v)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n-values", nargs="+", type=int, default=[64, 128, 256])
    parser.add_argument("--radix", type=int, default=8,
                        help="ntt_top radix to compare against (default 8)")
    args = parser.parse_args()

    R = args.radix
    n_vals = args.n_values

    # Print header
    SEP = "=" * 115
    print()
    print(SEP)
    print(f"  SCALING COMPARISON: ntt_top (R={R}) vs bivar_ntt_top (L=8)")
    print(f"  Device: Kintex-7 xc7k160tfbg484-2  |  q = 65537  |  L=8 fixed for bivar")
    print(f"  Architecture (Phase 4): single TIME-SHARED ModMul bank of R pipelined")
    print(f"  mod_mul_fermat instances (3-stage), matching the paper's Fig. 6.")
    print(f"  Rows marked [ref] are from Xing et al. (2025) Table IV (N=256 only).")
    print(SEP)

    col_w = 10
    hdr = (
        f"{'N':>5}  {'Design':>18}  {'LUT':>{col_w}}  {'DSP':>{col_w}}  "
        f"{'Fmax(MHz)':>{col_w}}  {'Cycles':>{col_w}}  {'Time(us)':>{col_w}}  "
        f"{'LUT-ATP':>{col_w}}  {'DSP-ATP':>{col_w}}"
    )
    print()
    print(hdr)
    print("-" * len(hdr))

    ratio_rows = []

    for n in n_vals:
        # ---- ntt_top (our implementation) ----
        ntt_path = SYNTH_DIR / f"results_r{R}_n{n}" / "metrics_raw.txt"
        ntt_m    = read_metrics(ntt_path)
        ntt_lut  = get_int(ntt_m, "LUT")
        ntt_dsp  = get_int(ntt_m, "DSP") if ntt_m else PRED_DSP_NTT8
        ntt_fmax = get_float(ntt_m, "FMAX_MHZ")
        ntt_cyc  = SIM_CYCLES_NTT.get((R, n))
        ntt_time = (ntt_cyc / ntt_fmax) if (ntt_cyc and ntt_fmax) else None
        ntt_lut_atp = (ntt_lut * ntt_cyc) if (ntt_lut and ntt_cyc) else None
        ntt_dsp_atp = (ntt_dsp * ntt_cyc) if (ntt_dsp and ntt_cyc) else None

        # ---- ntt_top (paper reference) ----
        paper_ref = PAPER_REF_NTT.get((R, n))

        # ---- bivar_ntt_top ----
        biv_path = SYNTH_DIR / f"results_bivar_n{n}" / "metrics_raw.txt"
        biv_m    = read_metrics(biv_path)
        biv_lut  = get_int(biv_m, "LUT")
        biv_dsp  = get_int(biv_m, "DSP") if biv_m else PRED_DSP_BIVAR
        biv_fmax = get_float(biv_m, "FMAX_MHZ")
        biv_cyc  = SIM_CYCLES_BIVAR.get(n)
        biv_time = (biv_cyc / biv_fmax) if (biv_cyc and biv_fmax) else None
        biv_lut_atp = (biv_lut * biv_cyc) if (biv_lut and biv_cyc) else None
        biv_dsp_atp = (biv_dsp * biv_cyc) if (biv_dsp and biv_cyc) else None

        def _row(label, lut, dsp, fmax, cyc, time, lut_atp, dsp_atp):
            print(
                f"{n:>5}  {label:>18}  "
                f"{fmt(lut):>{col_w}}  {fmt(dsp):>{col_w}}  "
                f"{fmt(fmax, '.1f') if fmax else 'N/A':>{col_w}}  {fmt(cyc):>{col_w}}  "
                f"{fmt(time, '.2f') if time else 'N/A':>{col_w}}  "
                f"{fmt(lut_atp):>{col_w}}  {fmt(dsp_atp):>{col_w}}"
            )

        _row(f"ntt R={R} (ours)", ntt_lut, ntt_dsp, ntt_fmax, ntt_cyc,
             ntt_time, ntt_lut_atp, ntt_dsp_atp)

        if paper_ref:
            p_lut  = paper_ref["LUT"]
            p_dsp  = paper_ref["DSP"]
            p_fmax = paper_ref["Fmax"]
            p_cyc  = paper_ref["cycles"]
            p_time = p_cyc / p_fmax
            p_latp = p_lut * p_cyc
            p_datp = p_dsp * p_cyc
            _row(f"ntt R={R} [ref]", p_lut, p_dsp, p_fmax, p_cyc,
                 p_time, p_latp, p_datp)

        _row("bivar L=8 (ours)", biv_lut, biv_dsp, biv_fmax, biv_cyc,
             biv_time, biv_lut_atp, biv_dsp_atp)

        if ntt_dsp_atp and biv_dsp_atp:
            ratio_ours = ntt_dsp_atp / biv_dsp_atp
            ratio_rows.append((n, "ours", ratio_ours, ntt_dsp_atp, biv_dsp_atp))
            print(f"{'':>5}  {'DSP-ATP (ours)':>18}  "
                  f"{'ntt/bivar = ' + f'{ratio_ours:.2f}x':>{col_w * 4 + 6}}"
                  f"  (bivar {'better' if ratio_ours > 1 else 'worse'})")

        if paper_ref and biv_dsp_atp:
            p_datp = paper_ref["DSP"] * paper_ref["cycles"]
            ratio  = p_datp / biv_dsp_atp
            ratio_rows.append((n, "paper", ratio, p_datp, biv_dsp_atp))
            print(f"{'':>5}  {'DSP-ATP [ref]':>18}  "
                  f"{'paper ntt/bivar = ' + f'{ratio:.2f}x':>{col_w * 4 + 6}}"
                  f"  (bivar {'better' if ratio > 1 else 'worse'})")

        print()

    # ---- Summary ----
    print(SEP)
    print("  DSP-ATP comparison (DSP count x latency cycles, lower is better):")
    print(f"  {'N':>5}  {'vs':>8}  {'ntt DSP-ATP':>14}  {'bivar DSP-ATP':>14}  {'ntt/bivar':>10}  note")
    print(f"  {'-'*5}  {'-'*8}  {'-'*14}  {'-'*14}  {'-'*10}  ----")
    for n, src, ratio, ntt_val, biv_val in ratio_rows:
        note = "bivar better" if ratio > 1 else "bivar worse"
        tag_map = {"ours": "[ours]", "paper": "[ref]"}
        tag = tag_map.get(src, src)
        print(f"  {n:>5}  {tag:>10}  {ntt_val:>14}  {biv_val:>14}  {ratio:>9.2f}x  {note}")

    if not ratio_rows:
        print("  (No data available -- run synthesis first)")

    print()
    print("  Cycles: our implementations = TOTAL (includes 2N I/O load + compute + output).")
    print("  [ref] cycles = TOTAL for 2NTT+1PWM+1INTT from Xing et al. (2025) Table IV.")
    print("  Note: paper uses memory cohabitation (A and B in same banks), so no I/O overhead.")
    print("  ATP = resource_count x cycles (lower is better).")
    print()
    print("  PHASE 4 IMPLEMENTATION (matches paper architecture):")
    print("   - Single TIME-SHARED ModMul bank: R pipelined mod_mul_fermat (3-stage).")
    print("     DSP count: R=8 -> 8 DSPs, R=4 -> 4 DSPs (exact paper match).")
    print("   - Registered orig_addrs / tw_step in ctrl_unit (breaks long combinational path).")
    print("   - 4-cycle write-back delay pipeline in ntt_top + 1-cycle INTT_DRAIN for OUTPUT.")
    print("   - bivar: 1 time-shared bank of L=8 mod_muls => ~8 DSPs (predicted).")
    print("")
    print("  REMAINING GAPS vs paper:")
    print("   - Fmax 55 MHz (R=8) vs paper 301 MHz: critical path is 54 logic levels through")
    print("     interconnect MUX (27 CARRY4 modular subtractions).  Needs barrel-shift")
    print("     restructuring OR registered bank_dout + 2nd alignment shift (future work).")
    print("   - Device: Kintex-7 -2 is ~15-20% slower than paper's Virtex-7 -3 (fixed gap).")
    print("   - Cycles: paper has memory cohabitation (no separate LOAD/OUTPUT phases).")
    print("     Our explicit 2N LOAD + 2N OUTPUT contribute 512 cycles overhead at N=256.")
    print()
    print("  WHAT BIVAR CONTRIBUTES (independent of implementation quality):")
    print("   - All butterfly multiplications are shift-only for L=8, N<=256 (verified)")
    print("   - Full multiplication count: O(N) = 7N  vs O(N log N) for monolithic NTT")
    print("   - Same architectural DSP count as ntt_top (~8 DSPs, time-shared)")
    print("   - To close cycle count gap: memory cohabitation (overlap LOAD with NTT1)")
    print()
    print("  Run synthesis:")
    print("    .\\synth\\vivado_run_all_metrics.ps1 -VivadoPath 'D:\\Xilinx\\Vivado\\2022.2\\bin\\vivado.bat'")
    print(SEP)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
