#!/usr/bin/env python3
"""
gen_hier_dN_L4.py
Emit rtl_hier_ntt/hier_d{D}_L4_top.v for a given decomposition depth D, L=4.

The d-variate hierarchical NTT polyMul has a fully regular structure (see the
hand-written, verified hier_d5_L4_top.v).  This generator parameterises that
structure over D so d=6, d=7, ... can be produced mechanically.

Axes i_{D-1}..i0.  L=4 (2-bit fields).  N=L^D.
  LOG_LANES=2, LOG_DEPTH=2*(D-1), LOGN=2*D, TW_BITS=2*D+1.
Banking: bank=(i0+i1+...+i_{D-1}) mod L; pos=i1+L*i2+...+L^{D-2}*i_{D-1}.

Pipeline taps d5 (mul), d8 (NTT), d12 (NTT+mul) — identical to d=5.
"""
import sys

L = 4

def opname(j):
    # field 0 -> op_a, 1 -> op_b, ...
    return "op_" + chr(ord('a') + j)

def gen(D):
    N_axes = D
    NOP = D - 1                      # number of op_count fields
    LOG_DEPTH = 2 * (D - 1)
    LOGN = 2 * D
    nstates = 6 * D + 2
    sbits = (nstates - 1).bit_length()
    out = []
    P = out.append

    P(f"// =============================================================================")
    P(f"// hier_d{D}_L4_top.v   (GENERATED by scripts/gen_hier_dN_L4.py)")
    P(f"// {D}-variate hierarchical NTT negacyclic polyMul.  L=4, N=L^{D}={L**D}.")
    P(f"// Axes i{D-1}..i0.  bank=(sum i_j) mod L; pos=i1+L*i2+...+L^{D-2}*i_{D-1}.")
    P(f"// Pipeline taps d5/d8/d12.  ntt_start uses state_d[1]/valid_d[1] (and")
    P(f"// state_d[5]/valid_d[5] for FWD_L0) so the start aligns with data arrival")
    P(f"// at the sub-NTT (fixes the last-issue direction-flip bug).")
    P(f"// =============================================================================")
    P(f"`ifndef _HIER_D{D}_L4_TOP_GUARD")
    P(f"`define _HIER_D{D}_L4_TOP_GUARD")
    P("")
    P(f"module hier_d{D}_L4_top #(")
    P(f"    parameter B       = 16,")
    P(f"    parameter L       = {L},")
    P(f"    parameter N       = {'*'.join(['L']*D)},")
    P(f"    parameter WWIDTH  = B + 1,")
    P(f"    parameter LOGN    = {LOGN},")
    P(f"    parameter TW_BITS = LOGN + 1")
    P(f")(")
    P(f"    input  wire              clk,")
    P(f"    input  wire              rst,")
    P(f"    input  wire              start,")
    P(f"    input  wire [WWIDTH-1:0] data_in_a,")
    P(f"    input  wire [WWIDTH-1:0] data_in_b,")
    P(f"    output reg  [WWIDTH-1:0] data_out,")
    P(f"    output reg               data_out_valid,")
    P(f"    output reg               done,")
    P(f"    output reg  [31:0]       cycle_count")
    P(f");")
    P("")

    # ---- state encoding ----
    states = []
    states.append("ST_IDLE")
    states.append("ST_LOAD")
    for ab in ('A', 'B'):
        for s in range(D):
            states.append(f"ST_FWD_L{s}_{ab}")
            if s < D - 1:
                states.append(f"ST_FWD_XTW{s+1}_{ab}")
    states.append("ST_PWM")
    # INV: L_{D-1}, XTW_{D-1}, L_{D-2}, XTW_{D-2}, ..., XTW1, L0
    for s in range(D - 1, -1, -1):
        states.append(f"ST_INV_L{s}")
        if s > 0:
            states.append(f"ST_INV_XTW{s}")
    states.append("ST_OUTPUT")
    states.append("ST_DONE")

    P(f"    localparam [{sbits-1}:0]")
    for i, s in enumerate(states):
        term = ";" if i == len(states) - 1 else ","
        P(f"        {s:<14} = {sbits}'d{i}{term}")
    P("")
    P(f"    localparam integer SCAN_CYCLES = N / L;")
    P(f"    localparam integer DRAIN       = 12;")
    P(f"    localparam integer SCAN_LEN    = SCAN_CYCLES + DRAIN;")
    P("")
    P(f"    reg [{sbits-1}:0] state;")
    P(f"    reg [LOGN:0]   op_count;")
    P(f"    wire           issue_valid;")
    P("")
    # ---- delay pipeline ----
    P(f"    reg [{sbits-1}:0] state_d   [1:12];")
    P(f"    reg [LOGN:0]   opcnt_d   [1:12];")
    P(f"    reg            valid_d   [1:12];")
    P(f"    integer ds;")
    P(f"    always @(posedge clk or posedge rst) begin")
    P(f"        if (rst) begin")
    P(f"            for (ds = 1; ds <= 12; ds = ds + 1) begin")
    P(f"                state_d[ds] <= {sbits}'d0;")
    P(f"                opcnt_d[ds] <= {{(LOGN+1){{1'b0}}}};")
    P(f"                valid_d[ds] <= 1'b0;")
    P(f"            end")
    P(f"        end else begin")
    P(f"            state_d[1] <= state; opcnt_d[1] <= op_count; valid_d[1] <= issue_valid;")
    P(f"            for (ds = 2; ds <= 12; ds = ds + 1) begin")
    P(f"                state_d[ds] <= state_d[ds-1];")
    P(f"                opcnt_d[ds] <= opcnt_d[ds-1];")
    P(f"                valid_d[ds] <= valid_d[ds-1];")
    P(f"            end")
    P(f"        end")
    P(f"    end")
    P("")
    P(f"    assign issue_valid =")
    P(f"        (state == ST_LOAD)    ? (op_count < N) :")
    P(f"        (state == ST_OUTPUT)  ? (op_count < N) :")
    P(f"        (state == ST_IDLE)    ? 1'b0 :")
    P(f"        (state == ST_DONE)    ? 1'b0 :")
    P(f"                                (op_count < SCAN_CYCLES);")
    P("")
    P(f"    localparam integer LANES     = L;")
    P(f"    localparam integer DEPTH     = {'*'.join(['L']*(D-1))};")
    P(f"    localparam integer LOG_LANES = 2;")
    P(f"    localparam integer LOG_DEPTH = {LOG_DEPTH};")
    P("")
    # op fields
    for j in range(NOP):
        P(f"    wire [LOG_LANES-1:0] {opname(j)} = op_count[{2*j+1}:{2*j}];")
    P("")
    # load fields
    for j in range(D):
        P(f"    wire [LOG_LANES-1:0] load_i{j} = op_count[{2*j+1}:{2*j}];")
    sum_load = " + ".join([f"load_i{j}" for j in range(D)])
    P(f"    wire [LOG_LANES-1:0] load_bank = ({sum_load}) & 2'h3;")
    P(f"    reg  [LOG_LANES-1:0] load_bank_d1;")
    P(f"    always @(posedge clk) load_bank_d1 <= load_bank;")
    # pos = {i_{D-1},...,i1}
    posfields = ", ".join([f"load_i{j}" for j in range(D-1, 0, -1)])
    P(f"    wire [LOG_DEPTH-1:0] load_pos  = {{{posfields}}};")
    P("")
    for j in range(D):
        P(f"    wire [LOG_LANES-1:0] load_i{j}_d5 = opcnt_d[5][{2*j+1}:{2*j}];")
    sum_load5 = " + ".join([f"load_i{j}_d5" for j in range(D)])
    P(f"    wire [LOG_LANES-1:0] load_bank_d5 = ({sum_load5}) & 2'h3;")
    posfields5 = ", ".join([f"load_i{j}_d5" for j in range(D-1, 0, -1)])
    P(f"    wire [LOG_DEPTH-1:0] load_pos_d5  = {{{posfields5}}};")
    P("")
    # rshift
    sum_op = " + ".join([opname(j) for j in range(NOP)])
    P(f"    wire [LOG_LANES-1:0] rshift_op = ({sum_op}) & 2'h3;")
    P("")

    # ---- rpos packs ----
    # axis_iX for X=1..D-1, plus broadcast, plus zero.
    # Build the pos field list (slots 1..D-1, i.e. i1..i_{D-1}) for each layout.
    def axis_pos_fields(X):
        # returns list of D-1 tokens for slots i1..i_{D-1} (low->high),
        # then we reverse for concatenation (MSB first).
        # op fields op_b..op_{NOP-1} (j=1..NOP-1) fill non-lane non-bank slots.
        # slot s in 1..D-1: if s==X -> gk ; else -> next op field (op_b, op_c,..)
        toks = [None]*(D)  # index by slot 1..D-1
        opj = 1  # start from op_b (field 1); op_a(field0)=i0 bank
        for s in range(1, D):
            if s == X:
                toks[s] = "gk[1:0]"
            else:
                toks[s] = opname(opj); opj += 1
        # concatenation MSB first: slot D-1 .. slot 1
        return [toks[s] for s in range(D-1, 0, -1)]
    def bc_pos_fields():
        # broadcast: lane=i0(bank). op_a..op_{NOP-1} fill slots 1..D-1.
        toks = [None]*(D)
        opj = 0
        for s in range(1, D):
            toks[s] = opname(opj); opj += 1
        return [toks[s] for s in range(D-1, 0, -1)]

    for X in range(1, D):
        P(f"    wire [LANES*LOG_DEPTH-1:0] rpos_axis_i{X}_pack;")
    P(f"    wire [LANES*LOG_DEPTH-1:0] rpos_broadcast_pack;")
    P(f"    wire [LANES*LOG_DEPTH-1:0] rpos_zero_pack;")
    P(f"    genvar gk;")
    P(f"    generate")
    P(f"        for (gk = 0; gk < LANES; gk = gk + 1) begin : g_rpos")
    for X in range(1, D):
        flds = ", ".join(axis_pos_fields(X))
        P(f"            assign rpos_axis_i{X}_pack [gk*LOG_DEPTH +: LOG_DEPTH] = {{{flds}}};")
    flds = ", ".join(bc_pos_fields())
    P(f"            assign rpos_broadcast_pack[gk*LOG_DEPTH +: LOG_DEPTH] = {{{flds}}};")
    P(f"            assign rpos_zero_pack     [gk*LOG_DEPTH +: LOG_DEPTH] = {{LOG_DEPTH{{1'b0}}}};")
    P(f"        end")
    P(f"    endgenerate")
    P("")

    # ---- wpos packs at taps 5,8,12 ----
    def axis_wpos_fields(X, tap):
        toks = [None]*(D)
        opj = 1
        for s in range(1, D):
            if s == X:
                toks[s] = "gk[1:0]"
            else:
                toks[s] = f"opcnt_d[{tap}][{2*opj+1}:{2*opj}]"; opj += 1
        return [toks[s] for s in range(D-1, 0, -1)]
    def bc_wpos_fields(tap):
        toks = [None]*(D)
        opj = 0
        for s in range(1, D):
            toks[s] = f"opcnt_d[{tap}][{2*opj+1}:{2*opj}]"; opj += 1
        return [toks[s] for s in range(D-1, 0, -1)]

    for X in range(1, D):
        P(f"    wire [LANES*LOG_DEPTH-1:0] wpos_i{X}_d5, wpos_i{X}_d8, wpos_i{X}_d12;")
    P(f"    wire [LANES*LOG_DEPTH-1:0] wpos_bc_d5, wpos_bc_d8, wpos_bc_d12;")
    P(f"    generate")
    P(f"        for (gk = 0; gk < LANES; gk = gk + 1) begin : g_wpos")
    for tap in (5, 8, 12):
        for X in range(1, D):
            flds = ", ".join(axis_wpos_fields(X, tap))
            P(f"            assign wpos_i{X}_d{tap}[gk*LOG_DEPTH +: LOG_DEPTH] = {{{flds}}};")
        flds = ", ".join(bc_wpos_fields(tap))
        P(f"            assign wpos_bc_d{tap}[gk*LOG_DEPTH +: LOG_DEPTH] = {{{flds}}};")
    P(f"        end")
    P(f"    endgenerate")
    P("")
    for tap in (5, 8, 12):
        sm = " + ".join([f"opcnt_d[{tap}][{2*j+1}:{2*j}]" for j in range(NOP)])
        P(f"    wire [LOG_LANES-1:0] wshift_d{tap} = ({sm}) & 2'h3;")
    P("")

    # ---- input delay chain ----
    P(f"    reg [WWIDTH-1:0] in_a_d [1:5];")
    P(f"    reg [WWIDTH-1:0] in_b_d [1:5];")
    P(f"    integer dd;")
    P(f"    always @(posedge clk) begin")
    P(f"        in_a_d[1] <= data_in_a; in_b_d[1] <= data_in_b;")
    P(f"        for (dd = 2; dd <= 5; dd = dd + 1) begin")
    P(f"            in_a_d[dd] <= in_a_d[dd-1]; in_b_d[dd] <= in_b_d[dd-1];")
    P(f"        end")
    P(f"    end")
    P("")
    # ---- mul array + twiddle ----
    P(f"    reg  [L*WWIDTH-1:0]  mul_a_pack;")
    P(f"    reg  [L*WWIDTH-1:0]  mul_b_pack;")
    P(f"    wire [L*WWIDTH-1:0]  mul_out_pack;")
    P(f"    wire [L*WWIDTH-1:0]  tw_pack;")
    P(f"    wire [L*TW_BITS-1:0] tw_idx_pack;")
    P("")
    P(f"    function [TW_BITS-1:0] inv_tw_idx;")
    P(f"        input [TW_BITS-1:0] idx;")
    P(f"        begin inv_tw_idx = (((2*N) - idx) % (2*N)); end")
    P(f"    endfunction")
    P("")
    P(f"    genvar tg;")
    P(f"    generate")
    P(f"        for (tg = 0; tg < L; tg = tg + 1) begin : gen_tw_lanes")
    for j in range(NOP):
        P(f"            wire [LOG_LANES-1:0] o{chr(ord('a')+j)}_d0 = {opname(j)};")
    # pre-twist: psi^(op_a + L*op_b + ... + L^{D-2}*op_{D-1} + L^{D-1}*tg)
    preterms = [f"o{chr(ord('a')+j)}_d0" if j == 0 else f"{'L*'*j}o{chr(ord('a')+j)}_d0" for j in range(NOP)]
    preterms.append(f"{'L*'*(D-1)}tg")
    P(f"            wire [TW_BITS-1:0] tw_fwd_l0_idx = ({' + '.join(preterms)}) % (2*N);")
    # XTW1: 2*L^{D-2}*op_{last}*tg
    last_op = f"o{chr(ord('a')+NOP-1)}_d0"
    P(f"            wire [TW_BITS-1:0] tw_xtw1_idx = (2*{'L*'*(D-2)}{last_op}*tg) % (2*N);")
    # XTW_m (m>=2): 2*L^{D-1-m}*tg*(sum_{p=0}^{m-1} op_field * L^p) where op fields are the last m
    for m in range(2, D):
        lead = 'L*' * (D-1-m)
        # last m op fields: indices NOP-m .. NOP-1, powers L^{m-1}..L^0
        sumterms = []
        for p in range(m):
            opidx = NOP - m + p     # field index
            power = m - 1 - p
            tok = f"o{chr(ord('a')+opidx)}_d0"
            if power > 0:
                tok = f"{'L*'*power}{tok}"
            sumterms.append(tok)
        P(f"            wire [TW_BITS-1:0] tw_xtw{m}_idx = (2*{lead}tg*({' + '.join(sumterms)})) % (2*N);")
    # INV_L0 post-twist at d7
    for j in range(NOP):
        P(f"            wire [LOG_LANES-1:0] o{chr(ord('a')+j)}_d7 = opcnt_d[7][{2*j+1}:{2*j}];")
    preterms7 = [f"o{chr(ord('a')+j)}_d7" if j == 0 else f"{'L*'*j}o{chr(ord('a')+j)}_d7" for j in range(NOP)]
    preterms7.append(f"{'L*'*(D-1)}tg")
    P(f"            wire [TW_BITS-1:0] tw_inv_l0_idx_d7 = inv_tw_idx(({' + '.join(preterms7)}) % (2*N));")
    for m in range(1, D):
        P(f"            wire [TW_BITS-1:0] tw_inv_xtw{m}_idx = inv_tw_idx(tw_xtw{m}_idx);")
    # tw_idx mux
    P(f"            assign tw_idx_pack[tg*TW_BITS +: TW_BITS] =")
    P(f"                (state_d[7] == ST_INV_L0) ? tw_inv_l0_idx_d7 :")
    P(f"                ((state == ST_FWD_L0_A) || (state == ST_FWD_L0_B)) ? tw_fwd_l0_idx :")
    for m in range(1, D):
        P(f"                ((state == ST_FWD_XTW{m}_A) || (state == ST_FWD_XTW{m}_B)) ? tw_xtw{m}_idx :")
    for m in range(D-1, 0, -1):
        P(f"                (state == ST_INV_XTW{m}) ? tw_inv_xtw{m}_idx :")
    P(f"                {{TW_BITS{{1'b0}}}};")
    P("")
    P(f"            twiddle_gen #(.B(B), .LOGN(LOGN), .REGISTERED(1)) u_tw (")
    P(f"                .clk(clk), .idx(tw_idx_pack[tg*TW_BITS +: TW_BITS]),")
    P(f"                .tw_out(tw_pack[tg*WWIDTH +: WWIDTH]));")
    P(f"            (* DONT_TOUCH = \"true\" *) reg [WWIDTH-1:0] mul_a_r;")
    P(f"            (* DONT_TOUCH = \"true\" *) reg [WWIDTH-1:0] mul_b_r;")
    P(f"            always @(posedge clk) begin")
    P(f"                mul_a_r <= mul_a_pack[tg*WWIDTH +: WWIDTH];")
    P(f"                mul_b_r <= mul_b_pack[tg*WWIDTH +: WWIDTH];")
    P(f"            end")
    P(f"            mod_mul_fermat #(.B(B), .PIPELINED(1)) u_mul (")
    P(f"                .clk(clk), .rst(rst), .a(mul_a_r), .b(mul_b_r),")
    P(f"                .result(mul_out_pack[tg*WWIDTH +: WWIDTH]));")
    P(f"        end")
    P(f"    endgenerate")
    P("")
    # ---- sub-NTT ----
    P(f"    reg [L*WWIDTH-1:0] ntt_in_pack;")
    P(f"    reg [L*WWIDTH-1:0] ntt_in_reg;")
    P(f"    reg                ntt_start, ntt_start_d1;")
    P(f"    reg                ntt_inverse, ntt_inverse_d1;")
    P(f"    always @(posedge clk) begin")
    P(f"        ntt_in_reg <= ntt_in_pack;")
    P(f"        ntt_start_d1 <= ntt_start; ntt_inverse_d1 <= ntt_inverse;")
    P(f"    end")
    # ntt_start uses state_d[1]/valid_d[1], FWD_L0 uses state_d[5]/valid_d[5]
    fwd_nott_l0 = []
    invL = []
    fwdL_other = []
    for s in range(1, D):
        fwdL_other.append(f"ST_FWD_L{s}_A"); fwdL_other.append(f"ST_FWD_L{s}_B")
    for s in range(D):
        invL.append(f"ST_INV_L{s}")
    P(f"    always @(*) begin")
    P(f"        ntt_start = 1'b0; ntt_inverse = 1'b0;")
    P(f"        if ((state_d[5] == ST_FWD_L0_A || state_d[5] == ST_FWD_L0_B) && valid_d[5])")
    P(f"            ntt_start = 1'b1;")
    P(f"        else case (state_d[1])")
    # split into chunks for readability
    fl = ", ".join(fwdL_other)
    P(f"            {fl}: ntt_start = valid_d[1];")
    il = ", ".join(invL)
    P(f"            {il}: begin ntt_start = valid_d[1]; ntt_inverse = 1'b1; end")
    P(f"            default: ;")
    P(f"        endcase")
    P(f"    end")
    P("")
    P(f"    wire [L*WWIDTH-1:0] ntt_out_pack;")
    P(f"    sub_ntt4_bidir #(.B(B)) u_subntt (")
    P(f"        .clk(clk), .rst(rst), .start(ntt_start_d1), .inverse(ntt_inverse_d1),")
    P(f"        .in_norm(ntt_in_reg), .out_norm(ntt_out_pack), .valid());")
    P("")
    # ---- memories ----
    P(f"    `define BMEM_DECL(NM) \\")
    P(f"        wire [LANES*WWIDTH-1:0]    NM``_rdata; \\")
    P(f"        reg  [LOG_LANES-1:0]       NM``_rshift; \\")
    P(f"        reg  [LANES*LOG_DEPTH-1:0] NM``_rpos; \\")
    P(f"        reg  [LOG_LANES-1:0]       NM``_wshift; \\")
    P(f"        reg  [LANES*LOG_DEPTH-1:0] NM``_wpos; \\")
    P(f"        reg  [LANES*WWIDTH-1:0]    NM``_wdata; \\")
    P(f"        reg  [LANES-1:0]           NM``_we; \\")
    P(f"        banked_mem #(.WWIDTH(WWIDTH), .LANES(LANES), .DEPTH(DEPTH), \\")
    P(f"                     .LOG_LANES(LOG_LANES), .LOG_DEPTH(LOG_DEPTH), \\")
    P(f"                     .READ_LATENCY(0), .STORAGE(\"bram\")) u_``NM ( \\")
    P(f"            .clk(clk), \\")
    P(f"            .rshift(NM``_rshift), .rpos_pack(NM``_rpos), .rdata_pack(NM``_rdata), \\")
    P(f"            .wshift(NM``_wshift), .wpos_pack(NM``_wpos), .wdata_pack(NM``_wdata), \\")
    P(f"            .we_pack(NM``_we) );")
    P(f"    `BMEM_DECL(mem_a)")
    P(f"    `BMEM_DECL(mem_b)")
    P(f"    `BMEM_DECL(mem_scratch)")
    P("")
    P(f"    wire [LANES*WWIDTH-1:0] raw_a_rdata   = mem_a_rdata;")
    P(f"    wire [LANES*WWIDTH-1:0] raw_b_rdata   = mem_b_rdata;")
    P(f"    wire [LANES*WWIDTH-1:0] scratch_rdata = mem_scratch_rdata;")
    P("")
    P(f"    function [LANES*WWIDTH-1:0] broadcastN;")
    P(f"        input [WWIDTH-1:0] v; integer bi;")
    P(f"        begin broadcastN = {{LANES*WWIDTH{{1'b0}}}};")
    P(f"            for (bi=0; bi<LANES; bi=bi+1) broadcastN[bi*WWIDTH +: WWIDTH] = v;")
    P(f"        end")
    P(f"    endfunction")
    P("")

    # Layout helpers: read-layout for each phase.
    # FWD_L0 reads axis_i{D-1}; FWD_XTW1 reads axis_i{D-1}; FWD_Ls (s=1..D-1)
    #   reads axis_i{D-1-s} (broadcast if D-1-s==0); FWD_XTWm (m>=2) reads the
    #   NEXT NTT axis = i{D-1-m} (broadcast if 0).
    # INV mirrors.
    def fwd_read_layout_L(s):
        ax = D - 1 - s
        return "broadcast" if ax == 0 else f"axis_i{ax}"
    def fwd_read_layout_XTW(m):
        if m == 1:
            return f"axis_i{D-1}"   # in-place after L0
        ax = D - 1 - m
        return "broadcast" if ax == 0 else f"axis_i{ax}"
    # write layout: FWD_Ls writes its own axis layout (axis_i{D-1-s} or bc).
    #   FWD_XTWm writes same layout it read.
    def fwd_write_layout_L(s):
        return fwd_read_layout_L(s)
    def fwd_write_layout_XTW(m):
        return fwd_read_layout_XTW(m)

    # INV: INV_Ls transforms k -> i along axis s. reads axis_i{s} (bc if s==0).
    #   But first INV_L{D-1} reads from mem_a (the PWM product, broadcast).
    # Let's mirror d=5:
    #   INV_L{D-1}: read mem_a broadcast.  INV_XTW{D-1}: scratch broadcast.
    #   INV_L{s} (s<D-1): read axis_i{?}. In d=5: INV_L3 reads axis_i1, INV_L2
    #   reads axis_i2, INV_L1 reads axis_i3, INV_L0 reads axis_i4.
    # Pattern (d=5): INV_L{s} reads axis_i{D-1-s}? L3->i1 (D-1-s=5-1-3=1 ✓),
    #   L2->i2 (5-1-2=2 ✓), L1->i3 (5-1-1=3 ✓), L0->i4 (5-1-0=4 ✓). And
    #   INV_L4 -> broadcast (D-1-s=0). ✓
    #   INV_XTW{m} reads same layout as the INV_L that precedes consuming it:
    #   d=5 INV_XTW4 bc, INV_XTW3 axis_i1, INV_XTW2 axis_i2, INV_XTW1 axis_i3.
    #   i.e. INV_XTW{m} reads axis_i{D-1-m} (bc if 0).
    def inv_read_layout_L(s):
        ax = D - 1 - s
        return "broadcast" if ax == 0 else f"axis_i{ax}"
    def inv_read_layout_XTW(m):
        ax = D - 1 - m
        return "broadcast" if ax == 0 else f"axis_i{ax}"

    def rpos_name(layout):
        return f"rpos_{layout}_pack" if layout == "broadcast" else f"rpos_{layout}_pack"
    def wpos_name(layout, tap):
        if layout == "broadcast":
            return f"wpos_bc_d{tap}"
        # layout is axis_iX
        X = layout.split("axis_i")[1]
        return f"wpos_i{X}_d{tap}"

    # ---- mem_a driver ----
    P(f"    always @(*) begin")
    P(f"        mem_a_rshift = 2'd0; mem_a_rpos = rpos_zero_pack;")
    P(f"        mem_a_wshift = 2'd0; mem_a_wpos = rpos_zero_pack;")
    P(f"        mem_a_wdata = {{LANES*WWIDTH{{1'b0}}}}; mem_a_we = {{LANES{{1'b0}}}};")
    P(f"        case (state)")
    P(f"            ST_FWD_L0_A: begin mem_a_rshift = rshift_op; mem_a_rpos = {rpos_name(fwd_read_layout_L(0))}; end")
    P(f"            ST_PWM:      begin mem_a_rshift = rshift_op; mem_a_rpos = rpos_broadcast_pack; end")
    P(f"            ST_INV_L{D-1}:  begin mem_a_rshift = rshift_op; mem_a_rpos = rpos_broadcast_pack; end")
    P(f"            ST_OUTPUT:   begin mem_a_rshift = 2'd0; mem_a_rpos[load_bank*LOG_DEPTH +: LOG_DEPTH] = load_pos; end")
    P(f"            default: ;")
    P(f"        endcase")
    P(f"        // INV_L0 final result -> mem_a (d12, axis_i{D-1})")
    P(f"        if (state_d[12] == ST_INV_L0 && valid_d[12]) begin")
    P(f"            mem_a_wshift = wshift_d12; mem_a_wpos = {wpos_name('axis_i'+str(D-1),12)};")
    P(f"            mem_a_wdata = mul_out_pack; mem_a_we = {{LANES{{1'b1}}}};")
    P(f"        end")
    P(f"        else if (state_d[8] == ST_FWD_L{D-1}_A && valid_d[8]) begin")
    P(f"            mem_a_wshift = wshift_d8; mem_a_wpos = wpos_bc_d8;")
    P(f"            mem_a_wdata = ntt_out_pack; mem_a_we = {{LANES{{1'b1}}}};")
    P(f"        end")
    P(f"        else if (state_d[5] == ST_PWM && valid_d[5]) begin")
    P(f"            mem_a_wshift = wshift_d5; mem_a_wpos = wpos_bc_d5;")
    P(f"            mem_a_wdata = mul_out_pack; mem_a_we = {{LANES{{1'b1}}}};")
    P(f"        end")
    P(f"        else if (state_d[5] == ST_LOAD && valid_d[5]) begin")
    P(f"            mem_a_wpos[load_bank_d5*LOG_DEPTH +: LOG_DEPTH] = load_pos_d5;")
    P(f"            mem_a_wdata = broadcastN(in_a_d[5]); mem_a_we[load_bank_d5] = 1'b1;")
    P(f"        end")
    P(f"    end")
    P("")
    # ---- mem_b driver ----
    P(f"    always @(*) begin")
    P(f"        mem_b_rshift = 2'd0; mem_b_rpos = rpos_zero_pack;")
    P(f"        mem_b_wshift = 2'd0; mem_b_wpos = rpos_zero_pack;")
    P(f"        mem_b_wdata = {{LANES*WWIDTH{{1'b0}}}}; mem_b_we = {{LANES{{1'b0}}}};")
    P(f"        case (state)")
    P(f"            ST_FWD_L0_B: begin mem_b_rshift = rshift_op; mem_b_rpos = {rpos_name(fwd_read_layout_L(0))}; end")
    P(f"            ST_PWM:      begin mem_b_rshift = rshift_op; mem_b_rpos = rpos_broadcast_pack; end")
    P(f"            default: ;")
    P(f"        endcase")
    P(f"        if (state_d[8] == ST_FWD_L{D-1}_B && valid_d[8]) begin")
    P(f"            mem_b_wshift = wshift_d8; mem_b_wpos = wpos_bc_d8;")
    P(f"            mem_b_wdata = ntt_out_pack; mem_b_we = {{LANES{{1'b1}}}};")
    P(f"        end")
    P(f"        else if (state_d[5] == ST_LOAD && valid_d[5]) begin")
    P(f"            mem_b_wpos[load_bank_d5*LOG_DEPTH +: LOG_DEPTH] = load_pos_d5;")
    P(f"            mem_b_wdata = broadcastN(in_b_d[5]); mem_b_we[load_bank_d5] = 1'b1;")
    P(f"        end")
    P(f"    end")
    P("")
    # ---- mem_scratch driver ----
    P(f"    always @(*) begin")
    P(f"        mem_scratch_rshift = 2'd0; mem_scratch_rpos = rpos_zero_pack;")
    P(f"        mem_scratch_wshift = 2'd0; mem_scratch_wpos = rpos_zero_pack;")
    P(f"        mem_scratch_wdata = {{LANES*WWIDTH{{1'b0}}}}; mem_scratch_we = {{LANES{{1'b0}}}};")
    P(f"        case (state)")
    # FWD reads: XTW1..XTW{D-1}, L1..L{D-1}
    for m in range(1, D):
        lay = fwd_read_layout_XTW(m)
        P(f"            ST_FWD_XTW{m}_A, ST_FWD_XTW{m}_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = {rpos_name(lay)}; end")
    for s in range(1, D):
        lay = fwd_read_layout_L(s)
        P(f"            ST_FWD_L{s}_A, ST_FWD_L{s}_B: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = {rpos_name(lay)}; end")
    # INV reads: XTW{D-1}..XTW1, L{D-2}..L0  (INV_L{D-1} reads mem_a not scratch)
    for m in range(D-1, 0, -1):
        lay = inv_read_layout_XTW(m)
        P(f"            ST_INV_XTW{m}: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = {rpos_name(lay)}; end")
    for s in range(D-2, -1, -1):
        lay = inv_read_layout_L(s)
        P(f"            ST_INV_L{s}: begin mem_scratch_rshift = rshift_op; mem_scratch_rpos = {rpos_name(lay)}; end")
    P(f"            default: ;")
    P(f"        endcase")
    # writes
    # d12: FWD_L0 (mul+NTT)
    P(f"        if ((state_d[12] == ST_FWD_L0_A || state_d[12] == ST_FWD_L0_B) && valid_d[12]) begin")
    P(f"            mem_scratch_wshift = wshift_d12; mem_scratch_wpos = {wpos_name(fwd_write_layout_L(0),12)};")
    P(f"            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {{LANES{{1'b1}}}};")
    P(f"        end")
    # d8: FWD_L1..L{D-2} (NTT only; L{D-1} writes mem_a), INV_L{D-1}..INV_L1
    first = True
    for s in range(1, D-1):
        lay = fwd_write_layout_L(s)
        kw = "else if"
        P(f"        {kw} ((state_d[8] == ST_FWD_L{s}_A || state_d[8] == ST_FWD_L{s}_B) && valid_d[8]) begin")
        P(f"            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = {wpos_name(lay,8)};")
        P(f"            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {{LANES{{1'b1}}}};")
        P(f"        end")
    # INV_L{D-1} writes scratch broadcast (it read mem_a)
    P(f"        else if (state_d[8] == ST_INV_L{D-1} && valid_d[8]) begin")
    P(f"            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = wpos_bc_d8;")
    P(f"            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {{LANES{{1'b1}}}};")
    P(f"        end")
    # INV_L{D-2}..INV_L1 write their axis layout
    for s in range(D-2, 0, -1):
        lay = inv_read_layout_L(s)
        P(f"        else if (state_d[8] == ST_INV_L{s} && valid_d[8]) begin")
        P(f"            mem_scratch_wshift = wshift_d8; mem_scratch_wpos = {wpos_name(lay,8)};")
        P(f"            mem_scratch_wdata = ntt_out_pack; mem_scratch_we = {{LANES{{1'b1}}}};")
        P(f"        end")
    # d5: FWD_XTW1..XTW{D-1}, INV_XTW{D-1}..XTW1
    for m in range(1, D):
        lay = fwd_write_layout_XTW(m)
        P(f"        else if ((state_d[5] == ST_FWD_XTW{m}_A || state_d[5] == ST_FWD_XTW{m}_B) && valid_d[5]) begin")
        P(f"            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = {wpos_name(lay,5)};")
        P(f"            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {{LANES{{1'b1}}}};")
        P(f"        end")
    for m in range(D-1, 0, -1):
        lay = inv_read_layout_XTW(m)
        P(f"        else if (state_d[5] == ST_INV_XTW{m} && valid_d[5]) begin")
        P(f"            mem_scratch_wshift = wshift_d5; mem_scratch_wpos = {wpos_name(lay,5)};")
        P(f"            mem_scratch_wdata = mul_out_pack; mem_scratch_we = {{LANES{{1'b1}}}};")
        P(f"        end")
    P(f"    end")
    P("")
    # ---- ntt_in_pack mux ----
    P(f"    integer ci;")
    P(f"    always @(*) begin")
    P(f"        ntt_in_pack = {{L*WWIDTH{{1'b0}}}};")
    P(f"        if (state_d[5] == ST_FWD_L0_A || state_d[5] == ST_FWD_L0_B)")
    P(f"            ntt_in_pack = mul_out_pack;")
    P(f"        else case (state_d[1])")
    fwdL = ", ".join([f"ST_FWD_L{s}_A, ST_FWD_L{s}_B" for s in range(1, D)])
    invL_scratch = ", ".join([f"ST_INV_L{s}" for s in range(D-1)])  # INV_L0..INV_L{D-2}
    P(f"            {fwdL},")
    P(f"            {invL_scratch}: ntt_in_pack = scratch_rdata;")
    P(f"            ST_INV_L{D-1}: ntt_in_pack = mem_a_rdata;")
    P(f"            default: ;")
    P(f"        endcase")
    P(f"    end")
    P("")
    # ---- mul source mux ----
    P(f"    always @(*) begin")
    P(f"        mul_a_pack = {{L*WWIDTH{{1'b0}}}}; mul_b_pack = {{L*WWIDTH{{1'b0}}}};")
    P(f"        if (state_d[8] == ST_INV_L0) begin")
    P(f"            mul_a_pack = ntt_out_pack; mul_b_pack = tw_pack;")
    P(f"        end else begin")
    P(f"            for (ci = 0; ci < L; ci = ci + 1) begin")
    P(f"                case (state_d[1])")
    P(f"                    ST_FWD_L0_A: begin")
    P(f"                        mul_a_pack[ci*WWIDTH +: WWIDTH] = raw_a_rdata[ci*WWIDTH +: WWIDTH];")
    P(f"                        mul_b_pack[ci*WWIDTH +: WWIDTH] = tw_pack[ci*WWIDTH +: WWIDTH]; end")
    P(f"                    ST_FWD_L0_B: begin")
    P(f"                        mul_a_pack[ci*WWIDTH +: WWIDTH] = raw_b_rdata[ci*WWIDTH +: WWIDTH];")
    P(f"                        mul_b_pack[ci*WWIDTH +: WWIDTH] = tw_pack[ci*WWIDTH +: WWIDTH]; end")
    xtw_fwd = ", ".join([f"ST_FWD_XTW{m}_A, ST_FWD_XTW{m}_B" for m in range(1, D)])
    xtw_inv = ", ".join([f"ST_INV_XTW{m}" for m in range(1, D)])
    P(f"                    {xtw_fwd},")
    P(f"                    {xtw_inv}: begin")
    P(f"                        mul_a_pack[ci*WWIDTH +: WWIDTH] = scratch_rdata[ci*WWIDTH +: WWIDTH];")
    P(f"                        mul_b_pack[ci*WWIDTH +: WWIDTH] = tw_pack[ci*WWIDTH +: WWIDTH]; end")
    P(f"                    ST_PWM: begin")
    P(f"                        mul_a_pack[ci*WWIDTH +: WWIDTH] = mem_a_rdata[ci*WWIDTH +: WWIDTH];")
    P(f"                        mul_b_pack[ci*WWIDTH +: WWIDTH] = mem_b_rdata[ci*WWIDTH +: WWIDTH]; end")
    P(f"                    default: ;")
    P(f"                endcase")
    P(f"            end")
    P(f"        end")
    P(f"    end")
    P("")
    # ---- FSM ----
    # phase order list for transitions
    seq = []
    for ab in ('A','B'):
        for s in range(D):
            seq.append(f"ST_FWD_L{s}_{ab}")
            if s < D-1:
                seq.append(f"ST_FWD_XTW{s+1}_{ab}")
    seq.append("ST_PWM")
    for s in range(D-1, -1, -1):
        seq.append(f"ST_INV_L{s}")
        if s > 0:
            seq.append(f"ST_INV_XTW{s}")
    # seq starts at FWD_L0_A and ends at INV_L0 -> OUTPUT
    P(f"    always @(posedge clk or posedge rst) begin")
    P(f"        if (rst) begin")
    P(f"            state <= ST_IDLE; op_count <= {{(LOGN+1){{1'b0}}}}; cycle_count <= 32'd0;")
    P(f"            data_out <= {{WWIDTH{{1'b0}}}}; data_out_valid <= 1'b0; done <= 1'b0;")
    P(f"        end else begin")
    P(f"            data_out_valid <= 1'b0;")
    P(f"            case (state)")
    P(f"                ST_IDLE: begin done<=1'b0; op_count<={{(LOGN+1){{1'b0}}}}; cycle_count<=32'd0; if (start) state<=ST_LOAD; end")
    P(f"                ST_LOAD: begin cycle_count<=cycle_count+1;")
    P(f"                    if (op_count == N+11) begin op_count<=0; state<=ST_FWD_L0_A; end else op_count<=op_count+1; end")
    for i, st in enumerate(seq):
        nxt = seq[i+1] if i+1 < len(seq) else "ST_OUTPUT"
        P(f"                {st}: begin cycle_count<=cycle_count+1;")
        P(f"                    if (op_count == SCAN_LEN-1) begin op_count<=0; state<={nxt}; end else op_count<=op_count+1; end")
    P(f"                ST_OUTPUT: begin cycle_count<=cycle_count+1;")
    P(f"                    data_out <= mem_a_rdata[load_bank_d1*WWIDTH +: WWIDTH];")
    P(f"                    data_out_valid <= (op_count >= 1) && (op_count < N+1);")
    P(f"                    if (op_count == N+1) begin op_count<=0; state<=ST_DONE; end else op_count<=op_count+1; end")
    P(f"                ST_DONE: done <= 1'b1;")
    P(f"            endcase")
    P(f"        end")
    P(f"    end")
    P("")
    P(f"endmodule")
    P(f"`endif")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    D = int(sys.argv[1]) if len(sys.argv) > 1 else 6
    path = f"rtl_hier_ntt/hier_d{D}_L4_top.v"
    with open(path, "w") as f:
        f.write(gen(D))
    print(f"wrote {path}  (D={D}, N={L**D}, states={6*D+2})")
