#!/usr/bin/env python3
"""
vivado_metrics_extract.py
Extracts metrics from Vivado reports and generates Table IV format

Usage:
    python vivado_metrics_extract.py <results_dir>
    
    <results_dir>: Directory containing synth/results_r<R>_n<N>/ subdirectories
    
Output:
    Prints Table IV in markdown format
    Writes metrics to synth/TABLE_IV.txt
"""

import re
import os
import sys
from pathlib import Path
from typing import Dict, Tuple, Optional

class VivadoMetricsParser:
    """Parse Vivado synthesis/implementation reports"""
    
    def __init__(self, results_dir: Path):
        self.results_dir = Path(results_dir)
        self.metrics = {}
    
    def parse_utilization_report(self, rpt_file: Path) -> Dict[str, int]:
        """
        Extract LUT, FF, DSP, BRAM from utilization report
        
        Vivado reports typically have formats like:
        | Slice LUTs              |  1690 |
        | Slice Registers         |  1289 |
        | Block DSPs              |     4 |
        | Block RAMs              |     0 |
        """
        metrics = {
            'LUT': 0, 'FF': 0, 'DSP': 0, 'BRAM': 0
        }
        
        if not rpt_file.exists():
            print(f"[WARN] Report not found: {rpt_file}")
            return metrics
        
        with open(rpt_file, 'r') as f:
            text = f.read()
        
        # Pattern matches "| Slice LUTs | 1690 |" etc.
        patterns = {
            'LUT': r'Slice LUTs\s+\|\s+(\d+)',
            'FF': r'Slice Registers\s+\|\s+(\d+)',
            'DSP': r'Block DSPs\s+\|\s+(\d+)',
            'BRAM': r'Block RAMs\s+\|\s+(\d+)',
        }
        
        for key, pattern in patterns.items():
            match = re.search(pattern, text)
            if match:
                metrics[key] = int(match.group(1))
        
        return metrics
    
    def parse_timing_report(self, rpt_file: Path) -> Tuple[float, float]:
        """
        Extract WNS (Worst Negative Slack) and estimate Fmax
        
        Vivado timing_summary format:
        WNS(ns)      TNS(ns)  ...
        -18.437      -2123.1  ...
        
        Fmax = 1000 / (3.0 + |WNS|)  [assuming 3ns target period]
        """
        wns = None
        fmax = 300.0  # default estimate
        
        if not rpt_file.exists():
            print(f"[WARN] Report not found: {rpt_file}")
            return wns, fmax
        
        with open(rpt_file, 'r') as f:
            text = f.read()
        
        # Look for WNS line
        for line in text.split('\n'):
            if 'WNS(ns)' in line:
                # Next line should have the value
                continue
            match = re.search(r'([-+]?\d+\.?\d*)\s+', line)
            if match:
                try:
                    wns = float(match.group(1))
                    # Calculate Fmax: if WNS is negative (timing violation),
                    # actual period > 3ns; if positive (slack), use 3ns
                    if wns is not None:
                        if wns < 0:
                            period_ns = 3.0 - wns  # e.g., -18.437 -> 21.437ns
                        else:
                            period_ns = 3.0
                        fmax = 1000.0 / period_ns
                    break
                except ValueError:
                    pass
        
        return wns, fmax
    
    def extract_from_metrics_file(self, metrics_file: Path) -> Dict[str, float]:
        """Parse metrics_raw.txt generated by Tcl script"""
        metrics = {}
        
        if not metrics_file.exists():
            return metrics
        
        with open(metrics_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('#') or '=' not in line:
                    continue
                key, val = line.split('=', 1)
                key = key.strip()
                try:
                    # Try to parse as float first, then int
                    if '.' in val:
                        metrics[key] = float(val)
                    else:
                        metrics[key] = int(val)
                except ValueError:
                    metrics[key] = val
        
        return metrics
    
    def get_metrics_for_config(self, radix: int, n_degree: int) -> Optional[Dict]:
        """
        Get all metrics for a specific radix/degree configuration
        
        Returns: {'LUT': int, 'FF': int, 'DSP': int, 'BRAM': int,
                  'FMAX': float, 'Cycles': int, 'Time': float}
                 or None if not found
        """
        config_dir = self.results_dir / f"results_r{radix}_n{n_degree}"
        
        if not config_dir.exists():
            print(f"[INFO] Config dir not found: {config_dir}")
            return None
        
        metrics = {}
        
        # Try to get from metrics_raw.txt first
        metrics_file = config_dir / "metrics_raw.txt"
        if metrics_file.exists():
            parsed = self.extract_from_metrics_file(metrics_file)
            metrics.update(parsed)
        
        # Fall back to parsing reports directly
        if not metrics or 'LUT' not in metrics:
            util_reports = sorted(config_dir.glob("*utilization.rpt"))
            if util_reports:
                util_metrics = self.parse_utilization_report(util_reports[-1])
                metrics.update(util_metrics)
        
        if not metrics or 'FMAX_MHZ' not in metrics:
            timing_reports = sorted(config_dir.glob("*timing.rpt"))
            if timing_reports:
                wns, fmax = self.parse_timing_report(timing_reports[-1])
                metrics['WNS_NS'] = wns
                metrics['FMAX_MHZ'] = fmax
        
        return metrics if metrics else None


def format_table_iv(results_dir: Path) -> str:
    """Generate Table IV markdown format"""
    
    parser = VivadoMetricsParser(results_dir)
    
    # Configurations to report: (N, radix_configs)
    configs = [
        (256, [4, 8, 16]),
        (512, [4, 8, 16]),
        (1024, [4, 8, 16]),
    ]
    
    output = []
    output.append("| Work | Device | Modulus q | BFU | Radix | LUT/ATP | FF/ATP | DSP/ATP | BRAM/ATP | Freq(MHz) | Cycles | Time(us) |")
    output.append("|------|--------|-----------|-----|-------|---------|--------|---------|----------|-----------|--------|----------|")
    
    for n_degree, radix_list in configs:
        for radix in radix_list:
            metrics = parser.get_metrics_for_config(radix, n_degree)
            
            if metrics is None:
                continue
            
            lut = metrics.get('LUT', 0)
            ff = metrics.get('FF', 0)
            dsp = metrics.get('DSP', 0)
            bram = metrics.get('BRAM', 0)
            fmax = metrics.get('FMAX_MHZ', 300)
            cycles = metrics.get('CYCLES', 1000)
            time_us = metrics.get('TIME_US', cycles / fmax)
            
            # Calculate ATP (normalized by cycles)
            lut_atp = lut * cycles
            ff_atp = ff * cycles
            dsp_atp = dsp * cycles
            bram_atp = bram * cycles
            
            # Normalize for display (divide by some baseline to get fractional values like in Table IV)
            # Using approximate baseline from paper Table IV for reference
            # For now, show raw values - you can normalize later
            
            bfu = f"1*R{radix}"
            
            output.append(
                f"| Ours | Virtex-7 | 65537 (17-bit) | {bfu} | {radix} | "
                f"{lut}/{lut_atp} | {ff}/{ff_atp} | {dsp}/{dsp_atp} | {bram}/{bram_atp} | "
                f"{fmax:.0f} | {cycles} | {time_us:.1f} |"
            )
    
    return "\n".join(output)


def main():
    if len(sys.argv) < 2:
        results_dir = Path.cwd() / "synth"
    else:
        results_dir = Path(sys.argv[1])
    
    if not results_dir.exists():
        print(f"ERROR: Directory not found: {results_dir}")
        sys.exit(1)
    
    print("=" * 100)
    print("  TABLE IV METRICS EXTRACTION")
    print("=" * 100)
    print(f"Results directory: {results_dir}\n")
    
    table = format_table_iv(results_dir)
    print(table)
    
    # Write to file
    output_file = results_dir / "TABLE_IV.txt"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(table)
    
    print(f"\n[INFO] Table IV written to: {output_file}")


if __name__ == '__main__':
    main()
